"use client";

import { Download, Eye, Headphones, Plus, ShieldCheck, TrendingUp, Users } from "lucide-react";
import type { ReactNode } from "react";
import { useMemo, useState } from "react";

import type { KecamatanCitizen, KecamatanData } from "@/lib/kecamatan/data";
import { CitizenDrawer, HelpdeskDialog, ProposalDialog, StatusBadge } from "@/components/kecamatan/shared/workflow-panels";
import styles from "@/components/kecamatan/shared/kecamatan-ui.module.css";

export function KecamatanWarga({ data }: { data: KecamatanData }) {
  const [mode, setMode] = useState<"proposal" | "helpdesk" | "detail" | null>(null); const [selected, setSelected] = useState<KecamatanCitizen | null>(null); const [search, setSearch] = useState(""); const [village, setVillage] = useState(""); const [quick, setQuick] = useState(0);
  const filtered = useMemo(() => data.citizens.filter((item) => !search || `${item.name} ${item.maskedNik}`.toLowerCase().includes(search.toLowerCase())).filter((item) => !village || item.kelurahanId === village).filter((item) => !quick || (item.desil ?? 0) === quick || (quick === 3 && item.desil === 3) || (quick === 5 && (item.desil ?? 0) >= 4)), [data.citizens, search, village, quick]);
  const total = data.citizens.length; const priority = data.citizens.filter((item) => (item.desil ?? 9) <= 2).length; const vulnerable = data.citizens.filter((item) => item.desil === 3).length; const independent = data.citizens.filter((item) => (item.desil ?? 0) >= 4).length;
  function exportCsv() { const rows = [["Nama", "NIK Tersamar", "Kelurahan", "Desil", "Status"], ...filtered.map((item) => [item.name, item.maskedNik, item.kelurahan, String(item.desil ?? ""), item.proposalStatus])]; const blob = new Blob([rows.map((row) => row.map((cell) => `"${cell.replaceAll('"','""')}"`).join(",")).join("\n")], { type: "text/csv;charset=utf-8" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = `warga-mbi-${data.actor.district.toLowerCase()}.csv`; link.click(); URL.revokeObjectURL(link.href); }
  return <section aria-labelledby="kc-warga-title"><div className={styles.pageHeading}><div><h1 id="kc-warga-title">Master Data Warga MBI - Kecamatan {data.actor.district}</h1><p>Basis data warga MBI beserta status verifikasi dan riwayat rujukan kewilayahan.</p></div><div className={styles.headingActions}><button className={styles.secondary} onClick={exportCsv}><Download size={16} /> Ekspor Data</button><button className={styles.primary} onClick={() => setMode("proposal")}><Plus size={16} /> Tambah Usulan Warga</button></div></div>
    <div className={styles.summaryGrid}><Summary label="Total Warga MBI" value={total} note="Terpetakan pada wilayah akun" icon={<Users />} /><Summary label="Desil 1 & 2 (Prioritas)" value={priority} note="Prioritas intervensi" icon={<ShieldCheck />} /><Summary label="Desil 3 (Rentan)" value={vulnerable} note="Inkubasi ekonomi & kerja" icon={<TrendingUp />} /><Summary label="Desil 4 & 5 (Mandiri)" value={independent} note="Graduasi / mampu mandiri" icon={<ShieldCheck />} /></div>
    <section className={styles.card}><div className={styles.filters}><div className={styles.filterControls}><input className={styles.searchBox} aria-label="Cari warga" placeholder="NIK atau Nama..." value={search} onChange={(event) => setSearch(event.target.value)} /><select aria-label="Filter kelurahan" value={village} onChange={(event) => setVillage(event.target.value)}><option value="">Semua Kelurahan</option>{data.kelurahan.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div></div><div className={styles.chips} style={{ padding: "0 24px 16px" }}><button className={styles.action} onClick={() => setQuick(0)}>Semua ({total})</button><button className={styles.action} onClick={() => setQuick(1)}>Desil 1</button><button className={styles.action} onClick={() => setQuick(3)}>Desil 3</button><button className={styles.action} onClick={() => setQuick(5)}>Desil 4 &amp; 5</button></div>
      <div className={styles.desktopTable}><table><thead><tr><th>NIK &amp; Nama Warga</th><th>Kelurahan &amp; RT/RW</th><th>Tingkat Desil</th><th>OPD Tujuan / Status</th><th>Tanggal Terdata</th><th>Aksi</th></tr></thead><tbody>{filtered.map((item) => <tr key={item.id}><td><strong>{item.name}</strong><span className={styles.muted}>{item.maskedNik}</span></td><td>{item.kelurahan}<br /><span className={styles.muted}>RT {item.rt} / RW {item.rw}</span></td><td>Desil {item.desil ?? "—"}</td><td><StatusBadge status={item.proposalStatus} /></td><td>{item.registeredAt}</td><td><button className={styles.action} onClick={() => { setSelected(item); setMode("detail"); }}><Eye size={16} /> Detail</button></td></tr>)}</tbody></table></div>
      <div className={styles.mobileCards}>{filtered.map((item) => <article key={item.id}><header><div><h3>{item.name}</h3><span className={styles.muted}>{item.maskedNik} · {item.kelurahan}</span></div><StatusBadge status={item.proposalStatus} /></header><button className={styles.action} onClick={() => { setSelected(item); setMode("detail"); }}><Eye size={16} /> Detail</button></article>)}</div>{!filtered.length && <p className={styles.emptyState}>Belum ada data warga yang sesuai filter.</p>}<div className={styles.pagination}><p>Menampilkan 1–{filtered.length} dari {total} warga</p></div>
    </section>
    <div className={styles.dashboardBottom}><section className={styles.panel}><h2>Sebaran Validasi per Kelurahan</h2><p>Status data warga yang terpetakan pada tiap kelurahan.</p><div className={styles.distribution}>{data.kelurahan.map((item) => { const count = data.citizens.filter((citizen) => citizen.kelurahanId === item.id).length; const done = data.citizens.filter((citizen) => citizen.kelurahanId === item.id && citizen.proposalStatus !== "TERDATA").length; const pct = count ? Math.round(done / count * 100) : 0; return <div key={item.id}><div className={styles.barLabel}><strong>{item.name} ({count} warga)</strong><span>{pct}% terverifikasi</span></div><div className={styles.bar}><span style={{ width: `${pct}%` }} /></div></div>; })}</div></section><aside className={styles.panel}><Headphones size={28} /><h2>Hubungi Helpdesk Pusdatin Diskominfo</h2><p>Laporkan anomali data NIK, wilayah, atau kendala rujukan.</p><button className={styles.primary} onClick={() => setMode("helpdesk")}>Hubungi Helpdesk</button></aside></div>
    {mode === "proposal" && <ProposalDialog citizens={data.citizens} programs={data.programs} close={() => setMode(null)} />}{mode === "helpdesk" && <HelpdeskDialog citizens={data.citizens} close={() => setMode(null)} />}{mode === "detail" && selected && <CitizenDrawer citizen={selected} close={() => { setSelected(null); setMode(null); }} />}
  </section>;
}
function Summary({ label, value, note, icon }: { label: string; value: number; note: string; icon: ReactNode }) { return <article className={styles.summaryCard}><span className={styles.summaryIcon}>{icon}</span><div><p>{label}</p><strong>{value.toLocaleString("id-ID")}</strong><span className={styles.muted}>{note}</span></div></article>; }
