"use client";

import { ChevronLeft, ChevronRight, CircleCheckBig, HeartHandshake, Printer, TriangleAlert } from "lucide-react";
import { useMemo, useState } from "react";
import { Dialog, Drawer } from "@/components/dp3a/shared/dialog";
import styles from "@/components/dp3a/shared/dp3a-ui.module.css";
import type { Dp3aVerificationStatus, Dp3aProgram, Dp3aReferral, Dp3aReferralStatus, Dp3aServiceUnit } from "@/lib/dp3a/data";

type Mode = "start" | "progress" | "detail" | null;
function label(status: Dp3aReferralStatus) { if (status === "PERLU_DIPROSES") return "Perlu Diproses"; if (status === "DALAM_PROSES") return "Sedang Diverifikasi"; return "Kasus Terintervensi / Selesai"; }
function StatusBadge({ status }: { status: Dp3aReferralStatus }) { return <span className={`${styles.badge} ${status === "PERLU_DIPROSES" ? styles.badgeAmber : status === "SELESAI" ? styles.badgeGreen : ""}`}>{label(status)}</span>; }
function rupiah(value: number | null) { return value === null ? "—" : new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 }).format(value); }

export function Dp3aDashboard({ initialReferrals, programs, units, summary, preview }: { initialReferrals: Dp3aReferral[]; programs: Dp3aProgram[]; units: Dp3aServiceUnit[]; summary: { newReferrals: number; processing: number; completed: number }; preview: boolean }) {
  const [referrals, setReferrals] = useState(initialReferrals); const [selected, setSelected] = useState<Dp3aReferral | null>(null); const [mode, setMode] = useState<Mode>(null); const [statusFilter, setStatusFilter] = useState(""); const [levelFilter, setLevelFilter] = useState(""); const [notice, setNotice] = useState(""); const [complete, setComplete] = useState(false);
  const filtered = useMemo(() => referrals.filter((item) => (!statusFilter || item.status === statusFilter) && (!levelFilter || item.serviceType.includes(levelFilter))), [referrals, statusFilter, levelFilter]);
  const today = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Jakarta", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date());
  function open(item: Dp3aReferral, next: Exclude<Mode, null>) { setSelected(item); setMode(next); setNotice(""); setComplete(false); }
  function close() { setSelected(null); setMode(null); setNotice(""); setComplete(false); }
  async function api(url: string, init: RequestInit) { if (preview) return { ok: true, json: async () => ({ caseId: crypto.randomUUID() }) }; return fetch(url, init); }

  async function submitStart(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!selected) return; const form = new FormData(event.currentTarget); const response = await api(`/api/dp3a/referrals/${selected.id}/start`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ programId: form.get("programId"), unitId: form.get("unitId"), caseType: form.get("caseType"), supportItem: form.get("supportItem"), startDate: form.get("startDate"), actionPlan: form.get("actionPlan") }) }); const body = await response.json().catch(() => ({})); if (!response.ok) return setNotice(body.error ?? "Penanganan tidak dapat dimulai."); const program = programs.find((item) => item.id === form.get("programId")); const unit = units.find((item) => item.id === form.get("unitId"));
    setReferrals((items) => items.map((item) => item.id === selected.id ? { ...item, caseId: body.caseId, status: "DALAM_PROSES", caseStatus: "VERIFIKASI", verificationStatus: "MENUNGGU", progress: 0, programId: program?.id ?? item.programId, program: program?.name ?? item.program, unitId: unit?.id ?? item.unitId, unit: unit?.name ?? item.unit, serviceType: String(form.get("caseType")), supportItem: String(form.get("supportItem")), notes: String(form.get("actionPlan")), plannedBudget: program?.budgetPerBeneficiary ?? 0, timeline: [...item.timeline, { id: crypto.randomUUID(), type: "STARTED", date: "Hari ini", note: "Rujukan diterima dan asesmen awal DP3A dimulai.", progress: 0 }] } : item)); setNotice("Penanganan kasus dimulai."); window.setTimeout(close, 500);
  }
  async function submitProgress(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!selected?.caseId) return; const form = new FormData(event.currentTarget); const isComplete = form.get("caseStatus") === "SELESAI"; const payload = isComplete ? { realizedAmount: Number(form.get("realizedAmount")), completionDate: form.get("completionDate"), supportItem: form.get("supportItem"), evaluation: form.get("evaluation") } : { progressPercent: Number(form.get("progressPercent")), verificationStatus: form.get("verificationStatus"), realizedAmount: Number(form.get("realizedAmount")), evaluation: form.get("evaluation") }; const response = await api(`/api/dp3a/cases/${selected.caseId}/${isComplete ? "complete" : "progress"}`, { method: isComplete ? "POST" : "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json().catch(() => ({})); if (!response.ok) return setNotice(body.error ?? "Progress tidak dapat disimpan."); const progress = isComplete ? 100 : Number(form.get("progressPercent")); const evaluation = String(form.get("evaluation"));
    setReferrals((items) => items.map((item) => item.id === selected.id ? { ...item, status: isComplete ? "SELESAI" : "DALAM_PROSES", caseStatus: isComplete ? "SELESAI" : "PENDAMPINGAN", verificationStatus: isComplete ? "LULUS" : String(form.get("verificationStatus")) as Dp3aVerificationStatus, progress, realizedAmount: Number(form.get("realizedAmount")), supportItem: isComplete ? String(form.get("supportItem")) : item.supportItem, notes: evaluation, timeline: [...item.timeline, { id: crypto.randomUUID(), type: isComplete ? "COMPLETED" : "PROGRESS_UPDATED", date: "Hari ini", note: evaluation, progress }] } : item)); setNotice(isComplete ? "Penanganan kasus selesai." : "Progress penanganan tersimpan."); window.setTimeout(close, 500);
  }
  const current = referrals === initialReferrals ? summary : { newReferrals: referrals.filter((x) => x.status === "PERLU_DIPROSES").length, processing: referrals.filter((x) => x.status === "DALAM_PROSES").length, completed: referrals.filter((x) => x.status === "SELESAI").length };
  return <section aria-labelledby="dp3a-title">
    <div className={styles.pageHeading}><div><h1 id="dp3a-title">Rujukan Masuk &amp; Penanganan Kasus</h1><p>Pengelolaan rujukan perlindungan khusus anak, pendampingan hukum, konseling psikologis, dan pemberdayaan perempuan MBI.</p></div></div>
    <div className={styles.summaryGrid}><article className={styles.summaryCard}><span className={styles.summaryIcon}><TriangleAlert size={27} /></span><div><p>Rujukan Baru<br />(Perlu Tindak Lanjut)</p><strong>{current.newReferrals}</strong></div></article><article className={styles.summaryCard}><span className={styles.summaryIcon}><HeartHandshake size={27} /></span><div><p>Dalam Proses Pendampingan</p><strong>{current.processing}</strong></div></article><article className={styles.summaryCard}><span className={styles.summaryIcon}><CircleCheckBig size={27} /></span><div><p>Kasus Terintervensi / Selesai</p><strong>{current.completed}</strong></div></article></div>
    <section className={styles.card} aria-label="Daftar rujukan masuk">{preview && <p className={styles.previewNote}>Mode pratinjau DP3A aktif untuk pengembangan lokal.</p>}<div className={styles.filters}><h2>Daftar Rujukan Masuk</h2><div className={styles.filterControls}><select aria-label="Filter status" value={statusFilter} onChange={(e) => setStatusFilter(e.target.value)}><option value="">Semua Status</option><option value="PERLU_DIPROSES">Perlu Diproses</option><option value="DALAM_PROSES">Dalam Proses</option><option value="SELESAI">Selesai</option></select><select aria-label="Filter jenis layanan" value={levelFilter} onChange={(e) => setLevelFilter(e.target.value)}><option value="">Semua Jenis</option><option>Pendampingan Hukum</option><option>Perlindungan Anak</option><option>Konseling Psikologis</option><option>Pemberdayaan Ekonomi</option></select></div></div>
      <div className={styles.desktopTable}><table><thead><tr><th>ID Rujukan / Warga</th><th>Tanggal</th><th>Jenis Layanan &amp; Kelurahan</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{filtered.map((item) => <tr key={item.id}><td><strong>{item.name}</strong><span className={styles.muted}>{item.maskedNik}<br />{item.code}</span></td><td>{item.date}</td><td>{item.serviceType}<br /><span className={styles.muted}>{item.kelurahan}</span></td><td><StatusBadge status={item.status} /></td><td><button className={`${styles.action} ${item.status === "PERLU_DIPROSES" ? styles.actionPrimary : ""}`} onClick={() => open(item, item.status === "PERLU_DIPROSES" ? "start" : item.status === "DALAM_PROSES" ? "progress" : "detail")}>{item.status === "PERLU_DIPROSES" ? "Proses Penanganan" : item.status === "DALAM_PROSES" ? "Update Progress" : "Detail"}</button></td></tr>)}</tbody></table></div>
      <div className={styles.mobileCards}>{filtered.map((item) => <article key={item.id}><header><div><h3>{item.name}</h3><span className={styles.muted}>{item.maskedNik}<br />{item.code}</span></div><StatusBadge status={item.status} /></header><dl><div><dt>Tanggal</dt><dd>{item.date}</dd></div><div><dt>Jenis Layanan</dt><dd>{item.serviceType}</dd></div></dl><button className={`${styles.action} ${item.status === "PERLU_DIPROSES" ? styles.actionPrimary : ""}`} onClick={() => open(item, item.status === "PERLU_DIPROSES" ? "start" : item.status === "DALAM_PROSES" ? "progress" : "detail")}>{item.status === "PERLU_DIPROSES" ? "Proses Penanganan" : item.status === "DALAM_PROSES" ? "Update Progress" : "Detail"}</button></article>)}</div>
      {!filtered.length && <p className={styles.emptyState}>Belum ada rujukan DP3A yang sesuai filter.</p>}<nav className={styles.pagination} aria-label="Halaman rujukan"><p>Menampilkan 1–{filtered.length} dari {referrals.length} data</p><div className={styles.pages}><span><ChevronLeft size={15} /></span><strong aria-current="page">1</strong><span><ChevronRight size={15} /></span></div></nav>
    </section>
    {selected && mode === "start" && <Dialog title={`Proses Penanganan DP3A — ${selected.code}`} close={close} footer={<><button className={styles.secondary} onClick={close}>Batal</button><button className={styles.primary} type="submit" form="start-dp3a">Simpan &amp; Proses Penanganan</button></>}><form id="start-dp3a" className={styles.form} onSubmit={submitStart}><div className={styles.identity}><small>Identitas Korban / Warga</small><h3>{selected.name}</h3><p>NIK: {selected.maskedNik} | Desil: Desil {selected.desil || "—"} | Kelurahan: {selected.kelurahan}</p><span className={styles.badge}>Layanan Perlindungan</span></div><label>Pilih Program Layanan DP3A<select name="programId" defaultValue={selected.programId ?? programs.find((x) => x.status === "AKTIF")?.id} required>{programs.filter((x) => x.status === "AKTIF").map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Unit Pelaksana / Tim Pendamping<select name="unitId" defaultValue={selected.unitId ?? units[0]?.id} required>{units.map((item) => <option key={item.id} value={item.id}>{item.name} — {item.category}</option>)}</select></label><label>Jenis Kasus / Kebutuhan<input name="caseType" defaultValue={selected.serviceType} minLength={2} maxLength={100} required /></label><label>Jenis Layanan / Bantuan<input name="supportItem" defaultValue={selected.supportItem} minLength={3} maxLength={500} required /></label><label>Jadwal Pendampingan / Konseling<input type="date" name="startDate" defaultValue={today} required /></label><label>Rencana Penanganan &amp; Catatan Rekomendasi<textarea name="actionPlan" defaultValue={selected.notes} minLength={10} maxLength={2000} required /></label>{notice && <p role="status">{notice}</p>}</form></Dialog>}
    {selected && mode === "progress" && <Dialog title={`Update Progress Penanganan — ${selected.code}`} close={close} footer={<><button className={styles.secondary} onClick={close}>Batal</button><button className={styles.primary} type="submit" form="progress-dp3a">{complete ? "Simpan & Selesaikan Penanganan" : "Simpan & Update Progress"}</button></>}><form id="progress-dp3a" className={styles.form} onSubmit={submitProgress}><div className={styles.identity}><small>Nama Warga</small><h3>{selected.name} ({selected.maskedNik})</h3><p>Desil {selected.desil || "—"} | {selected.kelurahan}<br />{selected.program}</p><span className={styles.badge}>{selected.caseStatus === "PENDAMPINGAN" ? "Dalam Pendampingan" : "Sedang Diverifikasi"}</span></div><label>Status Penanganan Baru<select name="caseStatus" defaultValue="PENDAMPINGAN" onChange={(e) => setComplete(e.target.value === "SELESAI")}><option value="PENDAMPINGAN">Dalam Penanganan / Pendampingan</option><option value="SELESAI">Kasus Terintervensi / Selesai</option></select></label>{!complete && <div className={styles.twoColumns}><label>Persentase Progress (%)<input name="progressPercent" type="number" min="1" max="99" defaultValue={selected.progress ?? 50} required /></label><label>Status Verifikasi Berkas<select name="verificationStatus" defaultValue={selected.verificationStatus ?? "MENUNGGU"}><option value="MENUNGGU">Dalam Verifikasi</option><option value="LULUS">Lulus Verifikasi &amp; SK Terbit</option><option value="DITOLAK">Dokumen Ditolak</option></select></label></div>}<label>Realisasi Pagu Bantuan (Rp)<input name="realizedAmount" type="number" min="0" max="1000000000000" defaultValue={selected.realizedAmount ?? selected.plannedBudget} required /></label>{complete && <><label>Layanan / Bantuan yang Diterima<input name="supportItem" defaultValue={selected.supportItem} minLength={3} maxLength={500} required /></label><label>Tanggal Penutupan Kasus<input name="completionDate" type="date" defaultValue={today} required /></label></>}<label>Catatan Progress Penanganan DP3A<textarea name="evaluation" defaultValue={selected.notes} minLength={10} maxLength={2000} required /></label>{notice && <p role="status">{notice}</p>}</form></Dialog>}
    {selected && mode === "detail" && <Drawer title={`Detail Penanganan Kasus — ${selected.code}`} close={close} footer={<><button className={styles.secondary} onClick={() => window.print()}><Printer size={16} /> Unduh Rekap (PDF)</button><button className={styles.secondary} onClick={close}>Tutup</button></>}><div className={styles.detailStack}><div className={styles.identity}><small>Nama Warga</small><h3>{selected.name}</h3><p>{selected.maskedNik}<br />Desil {selected.desil || "—"} | {selected.kelurahan}</p><span className={`${styles.badge} ${styles.badgeGreen}`}>Kasus Terintervensi / Selesai</span></div><div className={styles.twoColumns}><div className={styles.detailBox}><small>Ringkasan Penanganan DP3A</small><strong>{selected.supportItem}</strong></div><div className={styles.detailBox}><small>Total Pagu Terserap</small><strong>{rupiah(selected.realizedAmount)}</strong></div></div><div className={styles.detailBox}><small>Tim Pendamping &amp; Lembaga Pelaksana</small><strong>{selected.unit} — {selected.progress === 100 ? "Pulih & Mandiri" : `${selected.progress ?? 0}% progress`}</strong></div><section><h2>Riwayat Penanganan & Pendampingan</h2><div className={styles.timeline}>{selected.timeline.map((event) => <div key={event.id}><span className={styles.muted}>{event.date}</span><p>{event.note}</p></div>)}</div></section></div></Drawer>}
  </section>;
}
