"use client";

import { useRouter } from "next/navigation";
import { useState, type FormEvent, type ReactNode } from "react";
import { ChevronDown, ChevronUp } from "lucide-react";

import styles from "./formulir-asesmen.module.css";

type Props = { caseId:string; initial:Record<string,unknown>|null; official:{desil:number;pbi:boolean|null;pkh:boolean|null;bpnt:boolean|null}|null; completed:boolean };
function Accordion({title,children,initialOpen=true}:{title:string;children:ReactNode;initialOpen?:boolean}){const [open,setOpen]=useState(initialOpen);return <section className={styles.accordion}><button type="button" aria-expanded={open} onClick={()=>setOpen(!open)}><span>{title}</span>{open?<ChevronUp size={14} aria-hidden="true"/>:<ChevronDown size={14} aria-hidden="true"/>}</button>{open&&<div className={styles.accordionBody}>{children}</div>}</section>}
const value=(data:Record<string,unknown>|null,key:string)=>typeof data?.[key]==="string"?String(data[key]):"";
const checked=(data:Record<string,unknown>|null,key:string)=>data?.[key]===true;
function Radio({name,label,val,initial}:{name:string;label:string;val:string;initial:string}){return <label className={styles.choice}><input type="radio" name={name} value={val} defaultChecked={initial===val}/>{label}</label>}

export function AssessmentForm({caseId,initial,official,completed}:Props){const router=useRouter();const [busy,setBusy]=useState<"draft"|"complete"|null>(null);const [error,setError]=useState("");const [success,setSuccess]=useState("");
  async function submit(form:HTMLFormElement,mode:"draft"|"complete"){if(busy)return;setBusy(mode);setError("");setSuccess("");const f=new FormData(form);const body={rentangPendapatan:f.get("rentangPendapatan"),statusBekerja:f.get("statusBekerja"),jenisPekerjaan:f.get("jenisPekerjaan"),penghasilanBulanan:f.get("penghasilanBulanan"),pendidikanTertinggi:f.get("pendidikanTertinggi"),literasiDigital:f.get("literasiDigital"),penyakitKronisDisabilitas:f.get("penyakitKronisDisabilitas"),penyakitDetail:f.get("penyakitDetail"),balitaStunting:f.get("balitaStunting"),lansiaTanpaPendamping:f.get("lansiaTanpaPendamping"),anakPutusSekolahCount:f.get("anakPutusSekolahCount"),kelayakanRumah:f.get("kelayakanRumah"),airSanitasi:f.get("airSanitasi"),nikValid:f.has("nikValid"),kkTerbaru:f.has("kkTerbaru"),bpjsAktif:f.has("bpjsAktif"),rekeningBank:f.has("rekeningBank"),motivasiPerubahan:f.get("motivasiPerubahan"),keterampilan:f.get("keterampilan"),catatanPetugas:f.get("catatanPetugas")};try{const response=await fetch(`/api/dinsos/cases/${caseId}/assessment/${mode}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error??"Asesmen tidak dapat disimpan.");if(mode==="complete"){router.push(`/dinsos/kasus/${caseId}/hasil`);}else{setSuccess("Draft asesmen berhasil disimpan.");router.refresh();}}catch(e){setError(e instanceof Error?e.message:"Asesmen tidak dapat disimpan.");}finally{setBusy(null)}}
  return <form className={styles.form} onSubmit={(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();void submit(e.currentTarget,"draft")}}><fieldset disabled={completed||Boolean(busy)}>
    <Accordion title="1. Kemiskinan" initialOpen><div className={styles.grid}><label>Desil DTSEN (Read-only)<input value={official?.desil??"Belum tersedia"} readOnly/></label><label>Rentang Pendapatan<input name="rentangPendapatan" maxLength={100} defaultValue={value(initial,"rentang_pendapatan")} placeholder="Masukkan rentang sesuai pedoman Dinsos"/></label><div className={styles.full}><span>Status Bansos Aktif</span><div className={styles.choices}><label><input type="checkbox" checked={official?.pbi===true} readOnly/> PBI</label><label><input type="checkbox" checked={official?.pkh===true} readOnly/> PKH</label><label><input type="checkbox" checked={official?.bpnt===true} readOnly/> BPNT</label></div></div></div></Accordion>
    <Accordion title="2. Pekerjaan"><div className={styles.grid}><fieldset className={styles.full}><legend>Status Bekerja *</legend><div className={styles.choices}><Radio name="statusBekerja" label="Bekerja" val="BEKERJA" initial={value(initial,"status_bekerja")}/><Radio name="statusBekerja" label="Tidak Bekerja" val="TIDAK_BEKERJA" initial={value(initial,"status_bekerja")}/></div></fieldset><label className={styles.full}>Jenis Pekerjaan<input name="jenisPekerjaan" maxLength={200} defaultValue={value(initial,"jenis_pekerjaan")}/></label><label className={styles.full}>Penghasilan Bulanan *<input name="penghasilanBulanan" maxLength={100} defaultValue={value(initial,"penghasilan_bulanan")}/></label></div></Accordion>
    <Accordion title="3. Pendidikan"><div className={styles.grid}><label>Pendidikan Tertinggi *<input name="pendidikanTertinggi" maxLength={100} defaultValue={value(initial,"pendidikan_tertinggi")}/></label><label>Literasi Digital *<select name="literasiDigital" defaultValue={value(initial,"literasi_digital")}><option value="">Pilih</option><option>MAHIR</option><option>CUKUP</option><option>KURANG</option></select></label></div></Accordion>
    <Accordion title="4. Kesehatan"><div className={styles.grid}><fieldset><legend>Penyakit Kronis / Disabilitas *</legend><div className={styles.choices}><Radio name="penyakitKronisDisabilitas" label="Ada" val="ADA" initial={value(initial,"penyakit_kronis_disabilitas")}/><Radio name="penyakitKronisDisabilitas" label="Tidak Ada" val="TIDAK_ADA" initial={value(initial,"penyakit_kronis_disabilitas")}/></div></fieldset><label>Detail<input name="penyakitDetail" maxLength={1000} defaultValue={value(initial,"penyakit_detail")}/></label><label>Balita Stunting *<select name="balitaStunting" defaultValue={value(initial,"balita_stunting")}><option value="">Pilih</option><option value="YA">Ya</option><option value="TIDAK">Tidak</option><option value="TIDAK_ADA_BALITA">Tidak Ada Balita</option></select></label></div></Accordion>
    <Accordion title="5. Kondisi Keluarga"><div className={styles.grid}><label>Lansia/Disabilitas Tanpa Pendamping *<select name="lansiaTanpaPendamping" defaultValue={value(initial,"lansia_disabilitas_tanpa_pendamping")}><option value="">Pilih</option><option value="YA">Ya</option><option value="TIDAK">Tidak</option></select></label><label>Anak Putus Sekolah *<input type="number" min="0" name="anakPutusSekolahCount" defaultValue={initial?.anak_putus_sekolah_count==null?"":String(initial.anak_putus_sekolah_count)}/></label></div></Accordion>
    <Accordion title="6. Tempat Tinggal"><div className={styles.grid}><label>Kelayakan Rumah *<select name="kelayakanRumah" defaultValue={value(initial,"kelayakan_rumah")}><option value="">Pilih</option><option value="LAYAK">Layak</option><option value="TIDAK_LAYAK">Tidak Layak</option></select></label><label>Akses Air Bersih &amp; Sanitasi *<select name="airSanitasi" defaultValue={value(initial,"air_sanitasi")}><option value="">Pilih</option><option value="MEMADAI">Memadai</option><option value="TIDAK_MEMADAI">Tidak Memadai</option></select></label></div></Accordion>
    <Accordion title="7. Administrasi"><div className={styles.choices}><label><input type="checkbox" name="nikValid" defaultChecked={checked(initial,"nik_valid")}/> NIK Valid</label><label><input type="checkbox" name="kkTerbaru" defaultChecked={checked(initial,"kk_terbaru")}/> KK Terbaru</label><label><input type="checkbox" name="bpjsAktif" defaultChecked={checked(initial,"bpjs_aktif")}/> BPJS Aktif</label><label><input type="checkbox" name="rekeningBank" defaultChecked={checked(initial,"rekening_bank")}/> Rekening Bank</label></div></Accordion>
    <Accordion title="8. Kapasitas Individu"><div className={styles.grid}><label>Motivasi Perubahan (1–5) *<input type="number" min="1" max="5" name="motivasiPerubahan" defaultValue={initial?.motivasi_perubahan==null?"":String(initial.motivasi_perubahan)}/></label><label className={styles.full}>Keterampilan yang Dimiliki *<textarea name="keterampilan" maxLength={2000} defaultValue={value(initial,"keterampilan")}/></label><label className={styles.full}>Catatan Petugas<textarea name="catatanPetugas" maxLength={3000} defaultValue={value(initial,"catatan_petugas")}/></label></div></Accordion>
  </fieldset>{error&&<p role="alert" className={styles.error}>{error}</p>}{success&&<p role="status" className={styles.success}>{success}</p>}{completed?<p className={styles.readOnly}>Asesmen telah selesai dan bersifat read-only.</p>:<div className={styles.actions}><button type="submit" disabled={Boolean(busy)}>{busy==="draft"?"Menyimpan...":"Simpan sebagai Draft"}</button><button type="button" className={styles.primary} disabled={Boolean(busy)} onClick={(e)=>{const form=e.currentTarget.form;if(form)void submit(form,"complete")}}>{busy==="complete"?"Memproses...":"Selesaikan Asesmen"}</button></div>}</form>;
}
