import { execFileSync } from "node:child_process";
import { expect,test,type Page } from "@playwright/test";

async function login(page:Page){const identifier=process.env.E2E_KELURAHAN_IDENTIFIER??process.env.KELURAHAN_ADMIN_USERNAME??"admin.kelurahan";const password=process.env.E2E_KELURAHAN_PASSWORD??process.env.KELURAHAN_ADMIN_PASSWORD??process.env.SUPABASE_TEST_VILLAGE_PASSWORD??process.env.SUPABASE_TEST_ADMIN_PASSWORD;if(!password)throw new Error("Credential E2E Kelurahan belum tersedia.");await page.goto("/login");await page.getByLabel("Nama Pengguna atau NIP").fill(identifier);await page.getByLabel("Kata Sandi",{exact:true}).fill(password);await page.getByRole("button",{name:"Masuk",exact:true}).click();await expect(page).toHaveURL(/\/kelurahan$/u,{timeout:15_000});}
function rowFor(page:Page,name:string){return page.getByRole("row").filter({hasText:name});}
test.describe.serial("Kelurahan verification workspace",()=>{
  test.beforeAll(()=>{execFileSync(process.execPath,["scripts/dev/seed-kelurahan-fixtures.mjs"],{cwd:process.cwd(),env:process.env,stdio:"pipe"});});
  test.afterAll(()=>{execFileSync(process.execPath,["scripts/dev/cleanup-kelurahan-fixtures.mjs"],{cwd:process.cwd(),env:process.env,stdio:"pipe"});});
  test("usulan, penugasan, survei, dan handoff Kecamatan berjalan",async({page})=>{await page.setViewportSize({width:1366,height:900});await login(page);await expect(page.getByRole("heading",{name:"Antrian Kerja Verifikasi Kelurahan"})).toBeVisible();expect(await page.content()).not.toMatch(/\b\d{16}\b/u);let row=rowFor(page,"Uji Kelurahan Asep");await row.getByRole("button",{name:"Proses"}).click();let dialog=page.getByRole("dialog",{name:/Proses Verifikasi Kelurahan/u});await expect(dialog).toBeVisible();await dialog.getByRole("button",{name:"Simpan & Tugaskan Surveyor"}).click();await expect(dialog).toBeHidden();row=rowFor(page,"Uji Kelurahan Asep");await row.getByRole("button",{name:"Isi Survei"}).click();dialog=page.getByRole("dialog",{name:/Hasil Survei Lapangan/u});await dialog.getByRole("button",{name:"Simpan Hasil Verifikasi"}).click();await expect(dialog).toBeHidden();row=rowFor(page,"Uji Kelurahan Asep");await row.getByRole("button",{name:"Kirim"}).click();dialog=page.getByRole("dialog",{name:/Kirim Usulan Warga ke Kecamatan/u});await dialog.getByRole("button",{name:"Kirim Usulan ke Kecamatan"}).click();await expect(dialog).toBeHidden();await expect(rowFor(page,"Uji Kelurahan Asep").getByRole("button",{name:"Detail"})).toBeVisible();expect(await page.content()).not.toMatch(/\b\d{16}\b/u);});
  test("halaman usulan, survei, helpdesk, detail, dan mobile sesuai boundary",async({page})=>{await login(page);await page.getByRole("link",{name:"Usulan Warga Kelurahan"}).click();await expect(page.getByRole("heading",{name:/Usulan Warga Kelurahan/u})).toBeVisible();await rowFor(page,"Uji Kelurahan Ratna").getByRole("button",{name:"Detail"}).click();await expect(page.getByRole("dialog",{name:/Detail Usulan Warga/u})).toBeVisible();await page.getByRole("button",{name:"Tutup",exact:true}).last().click();await page.getByRole("link",{name:"Survei Lapangan"}).click();await expect(page.getByRole("heading",{name:/Survei Lapangan Kelurahan/u})).toBeVisible();await page.getByRole("link",{name:"Helpdesk Operator"}).click();await expect(page.getByRole("heading",{name:"Helpdesk Operator Kelurahan"})).toBeVisible();for(const url of["/kelurahan","/kelurahan/usulan","/kelurahan/survei","/kelurahan/helpdesk"]){await page.setViewportSize({width:390,height:844});await page.goto(url);await expect(page.locator("main h1")).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth),url).toBeLessThanOrEqual(1);expect(await page.content()).not.toMatch(/\b\d{16}\b/u);}});
});
