"use client";

import { CheckCircle2, ClipboardCheck, Clock3, Download, Eye, Plus } from "lucide-react";
import type { ReactNode } from "react";
import { useMemo, useState } from "react";

import type { KecamatanCitizen, KecamatanData } from "@/lib/kecamatan/data";
import { StatusBadge, SurveyAssignmentDialog, SurveyDrawer, SurveyResultDialog, SurveyReviewDialog } from "@/components/kecamatan/shared/workflow-panels";
import styles from "@/components/kecamatan/shared/kecamatan-ui.module.css";

type Mode = "assign" | "result" | "review" | "detail" | null;
export function KecamatanVerifikasi({ data }: { data: KecamatanData }) {
  const [selected, setSelected] = useState<KecamatanCitizen | null>(null); const [mode, setMode] = useState<Mode>(null); const [search, setSearch] = useState(""); const [status, setStatus] = useState("");
  const rows = useMemo(() => data.citizens.filter((item) => item.proposalId && item.proposalStatus !== "DIRUJUK" && item.proposalStatus !== "DITOLAK").filter((item) => !search || `${item.name} ${item.maskedNik}`.toLowerCase().includes(search.toLowerCase())).filter((item) => !status || item.survey?.status === status), [data.citizens, search, status]);
  function open(item: KecamatanCitizen, next: Mode) { setSelected(item); setMode(next); } function close() { setSelected(null); setMode(null); }
  return <section aria-labelledby="kc-verifikasi-title"><div className={styles.pageHeading}><div><h1 id="kc-verifikasi-title">Verifikasi Lapangan Kewilayahan</h1><p>Monitoring dan persetujuan hasil validasi faktual petugas PSM &amp; TKSK Kelurahan.</p></div><div className={styles.headingActions}><button className={styles.secondary} onClick={() => window.print()}><Download size={16} /> Ekspor Laporan</button><button className={styles.primary} onClick={() => { const item = rows.find((row) => row.proposalStatus === "MENUNGGU_SURVEI"); if (item) open(item, "assign"); }} disabled={!rows.some((row) => row.proposalStatus === "MENUNGGU_SURVEI")}><Plus size={16} /> Tugaskan Surveyor</button></div></div>
    <div className={styles.summaryGrid}><Summary label="Total Tugas Survei" value={data.surveySummary.total} icon={<ClipboardCheck />} /><Summary label="Selesai Diverifikasi" value={data.surveySummary.approved} icon={<CheckCircle2 />} /><Summary label="Menunggu Approval Kecamatan" value={data.surveySummary.waiting} icon={<Clock3 />} /></div>
    <section className={styles.card}><div className={styles.filters}><div className={styles.filterControls}><input className={styles.searchBox} aria-label="Cari survei" placeholder="Cari NIK, Nama, atau petugas..." value={search} onChange={(event) => setSearch(event.target.value)} /><select aria-label="Filter status survei" value={status} onChange={(event) => setStatus(event.target.value)}><option value="">Semua Status</option><option value="DITUGASKAN">Ditugaskan</option><option value="MENUNGGU_PERSETUJUAN">Perlu Approval</option><option value="DISETUJUI">Disetujui</option></select></div></div><div className={styles.desktopTable}><table><thead><tr><th>Nama Warga &amp; Kelurahan</th><th>Petugas Surveyor</th><th>Hasil Survei Lapangan</th><th>Status Approval</th><th>Aksi</th></tr></thead><tbody>{rows.map((item) => { const next: Mode = item.proposalStatus === "MENUNGGU_SURVEI" ? "assign" : item.survey?.status === "DITUGASKAN" || item.survey?.status === "SURVEI_ULANG" ? "result" : item.survey?.status === "MENUNGGU_PERSETUJUAN" ? "review" : "detail"; return <tr key={item.id}><td><strong>{item.name}</strong><span className={styles.muted}>{item.maskedNik}<br />{item.kelurahan} (RT {item.rt} / RW {item.rw})</span></td><td>{item.survey?.surveyor ?? "Belum ditugaskan"}</td><td><strong>{item.survey?.score ?? "—"}/100</strong><br /><span className={styles.muted}>Desil {item.survey?.factualDesil ?? item.desil ?? "—"}</span></td><td><StatusBadge status={item.survey?.status ?? item.proposalStatus} /></td><td><button className={`${styles.action} ${next !== "detail" ? styles.actionPrimary : ""}`} onClick={() => open(item, next)}>{next === "detail" ? <><Eye size={16} /> Detail</> : next === "assign" ? "Tugaskan" : next === "result" ? "Isi Hasil" : "Review & Approve"}</button></td></tr>; })}</tbody></table></div><div className={styles.mobileCards}>{rows.map((item) => <article key={item.id}><header><div><h3>{item.name}</h3><span className={styles.muted}>{item.kelurahan} · {item.survey?.surveyor ?? "Belum ditugaskan"}</span></div><StatusBadge status={item.survey?.status ?? item.proposalStatus} /></header></article>)}</div>{!rows.length && <p className={styles.emptyState}>Belum ada tugas survei yang sesuai filter.</p>}<div className={styles.pagination}><p>Menampilkan 1–{rows.length} dari {rows.length} data survei</p></div></section>
    {selected && mode === "assign" && <SurveyAssignmentDialog citizen={selected} close={close} />}{selected && mode === "result" && <SurveyResultDialog citizen={selected} close={close} />}{selected && mode === "review" && <SurveyReviewDialog citizen={selected} programs={data.programs} close={close} />}{selected && mode === "detail" && selected.survey && <SurveyDrawer citizen={selected} close={close} />}
  </section>;
}
function Summary({ label, value, icon }: { label: string; value: number; icon: ReactNode }) { return <article className={styles.summaryCard}><span className={styles.summaryIcon}>{icon}</span><div><p>{label}</p><strong>{value}</strong></div></article>; }
