"use client";

import { CheckCircle2, Clock3, Download, Eye, Plus, ShieldCheck } from "lucide-react";
import type { ReactNode } from "react";
import { useMemo, useState } from "react";

import type { KecamatanCitizen, KecamatanData } from "@/lib/kecamatan/data";
import { ReferralDialog, ReferralDrawer, StatusBadge } from "@/components/kecamatan/shared/workflow-panels";
import styles from "@/components/kecamatan/shared/kecamatan-ui.module.css";

export function KecamatanRujukan({ data }: { data: KecamatanData }) {
  const [selected, setSelected] = useState<KecamatanCitizen | null>(null); const [mode, setMode] = useState<"create" | "detail" | null>(null); const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [opd, setOpd] = useState("");
  const referrals = useMemo(() => data.citizens.filter((item) => item.referral).filter((item) => !search || `${item.name} ${item.referral?.code} ${item.maskedNik}`.toLowerCase().includes(search.toLowerCase())).filter((item) => !status || item.referral?.status === status).filter((item) => !opd || item.referral?.opdCode === opd), [data.citizens, search, status, opd]); const ready = data.citizens.find((item) => item.proposalStatus === "DISETUJUI");
  return <section aria-labelledby="kc-referral-title"><div className={styles.pageHeading}><div><h1 id="kc-referral-title">Pelacakan Rujukan Kewilayahan</h1><p>Monitoring status real-time tindak lanjut rujukan warga dari Kecamatan {data.actor.district} ke OPD teknis.</p></div><div className={styles.headingActions}><button className={styles.secondary} onClick={() => window.print()}><Download size={16} /> Ekspor Rekap</button><button className={styles.primary} disabled={!ready} onClick={() => { if (ready) { setSelected(ready); setMode("create"); } }}><Plus size={16} /> Buat Rujukan Baru</button></div></div>
    <div className={styles.summaryGrid}><Summary label="Total Rujukan Terkirim" value={data.referralSummary.total} icon={<ShieldCheck />} /><Summary label="Menunggu Respons OPD" value={data.referralSummary.waiting} icon={<Clock3 />} /><Summary label="Diterima & Diproses OPD" value={data.referralSummary.processing} icon={<ShieldCheck />} /><Summary label="Selesai / Intervensi" value={data.referralSummary.completed} icon={<CheckCircle2 />} /></div>
    <section className={styles.card}><div className={styles.filters}><div className={styles.filterControls}><input className={styles.searchBox} aria-label="Cari rujukan" placeholder="Cari No. Rujukan, NIK, Nama Warga..." value={search} onChange={(event) => setSearch(event.target.value)} /><select aria-label="Filter OPD" value={opd} onChange={(event) => setOpd(event.target.value)}><option value="">Semua OPD Tujuan</option>{Array.from(new Set(data.programs.map((item) => item.opdCode))).map((code) => <option key={code}>{code}</option>)}</select><select aria-label="Filter status rujukan" value={status} onChange={(event) => setStatus(event.target.value)}><option value="">Semua Status</option><option value="TERKIRIM">Menunggu Respons</option><option value="DITERIMA">Diterima</option><option value="DIPROSES">Diproses</option><option value="SELESAI">Selesai</option></select></div></div><div className={styles.desktopTable}><table><thead><tr><th>No. Rujukan &amp; Nama</th><th>Kelurahan</th><th>OPD Tujuan &amp; Kategori</th><th>Status Respons OPD</th><th>Tgl Dikirim</th><th>Aksi</th></tr></thead><tbody>{referrals.map((item) => <tr key={item.referral!.id}><td><strong>{item.name}</strong><span className={styles.muted}>{item.referral!.code} · {item.maskedNik}</span></td><td>{item.kelurahan}</td><td><strong>{item.referral!.opdName}</strong><span className={styles.muted}>{item.referral!.category}</span></td><td><StatusBadge status={item.referral!.status} /></td><td>{item.referral!.sentAt}</td><td><button className={styles.action} onClick={() => { setSelected(item); setMode("detail"); }}><Eye size={16} /> Detail</button></td></tr>)}</tbody></table></div><div className={styles.mobileCards}>{referrals.map((item) => <article key={item.referral!.id}><header><div><h3>{item.name}</h3><span className={styles.muted}>{item.referral!.code}<br />{item.referral!.opdName}</span></div><StatusBadge status={item.referral!.status} /></header><button className={styles.action} onClick={() => { setSelected(item); setMode("detail"); }}><Eye size={16} /> Detail</button></article>)}</div>{!referrals.length && <p className={styles.emptyState}>Belum ada rujukan kewilayahan yang sesuai filter.</p>}<div className={styles.pagination}><p>Menampilkan 1–{referrals.length} dari {data.referralSummary.total} rujukan</p></div></section>
    {selected && mode === "create" && <ReferralDialog citizen={selected} programs={data.programs} close={() => { setSelected(null); setMode(null); }} />}{selected && mode === "detail" && selected.referral && <ReferralDrawer citizen={selected} close={() => { setSelected(null); setMode(null); }} />}
  </section>;
}
function Summary({ label, value, icon }: { label: string; value: number; icon: ReactNode }) { return <article className={styles.summaryCard}><span className={styles.summaryIcon}>{icon}</span><div><p>{label}</p><strong>{value}</strong></div></article>; }
