"use client";

import { CheckCircle2, Eye, FileText, Printer, Send, ShieldCheck } from "lucide-react";
import { useRouter } from "next/navigation";
import { useMemo, useState } from "react";

import type { KecamatanCitizen, KecamatanProgram } from "@/lib/kecamatan/data";
import { Dialog, Drawer } from "./dialog";
import styles from "./kecamatan-ui.module.css";

export function StatusBadge({ status }: { status: string }) {
  const labels: Record<string, string> = { TERDATA: "Terdata", MENUNGGU_SURVEI: "Menunggu Survei", SURVEI_DITUGASKAN: "Verifikasi Kelurahan", MENUNGGU_PERSETUJUAN: "Validasi Kecamatan", DISETUJUI: "Siap Split Jalur OPD", DIRUJUK: "Split Jalur OPD", TERKIRIM: "Menunggu Respons OPD", DITERIMA: "Diterima OPD", DIPROSES: "Diproses OPD", SELESAI: "Selesai / Intervensi", DITOLAK: "Ditolak" };
  const tone = status === "SELESAI" || status === "DIRUJUK" || status === "DISETUJUI" ? styles.badgeGreen : status === "MENUNGGU_SURVEI" || status === "MENUNGGU_PERSETUJUAN" || status === "TERKIRIM" ? styles.badgeAmber : status === "DITOLAK" ? styles.statusRed : status === "TERDATA" ? styles.statusGray : styles.statusBlue;
  return <span className={`${styles.badge} ${tone}`}>{labels[status] ?? status.replaceAll("_", " ")}</span>;
}

async function request(url: string, method: string, payload: unknown) {
  const response = await fetch(url, { method, headers: { "content-type": "application/json" }, body: JSON.stringify(payload) });
  const body = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(body.error ?? "Permintaan tidak dapat diproses.");
  return body;
}

function useMutationDone(close: () => void) {
  const router = useRouter(); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function run(work: () => Promise<unknown>) { setBusy(true); setMessage(""); try { await work(); close(); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Permintaan gagal."); } finally { setBusy(false); } }
  return { run, busy, message };
}

export function ProposalDialog({ citizens, programs, close }: { citizens: KecamatanCitizen[]; programs: KecamatanProgram[]; close: () => void }) {
  const mutation = useMutationDone(close); const [lookup, setLookup] = useState(""); const [selectedId, setSelectedId] = useState(""); const [lookupMessage, setLookupMessage] = useState(""); const [lookupBusy, setLookupBusy] = useState(false);
  const selected = citizens.find((item) => item.id === selectedId) ?? null;
  async function check() { setLookupBusy(true); setLookupMessage(""); try { const body = await request("/api/kecamatan/warga/lookup", "POST", { nik: lookup }); setSelectedId(body.citizen.id); } catch (error) { setSelectedId(""); setLookupMessage(error instanceof Error ? error.message : "NIK tidak ditemukan."); } finally { setLookupBusy(false); } }
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected) return setLookupMessage("Periksa NIK warga terlebih dahulu."); const form = new FormData(event.currentTarget); await mutation.run(() => request("/api/kecamatan/usulan", "POST", { wargaId: selected.id, kelurahanId: selected.kelurahanId, rt: form.get("rt"), rw: form.get("rw"), initialDesil: Number(form.get("initialDesil")), targetProgramId: form.get("targetProgramId"), reason: form.get("reason") })); }
  return <Dialog title="Tambah Usulan Warga MBI Baru" close={close} footer={<><button className={styles.secondary} onClick={close}>Batal</button><button className={styles.primary} type="submit" form="kc-proposal" disabled={mutation.busy || !selected}><Send size={16} /> Simpan &amp; Penugasan Survei</button></>}><form id="kc-proposal" className={styles.form} onSubmit={submit}>
    <label>Nomor Induk Kependudukan (NIK)<div className={styles.inlineLookup}><input inputMode="numeric" value={lookup} onChange={(event) => setLookup(event.target.value.replace(/\D/gu, "").slice(0, 16))} placeholder="Masukkan 16 digit NIK" required /><button type="button" className={styles.primary} onClick={check} disabled={lookupBusy || lookup.length !== 16}><ShieldCheck size={16} /> {lookupBusy ? "Memeriksa..." : "Cek Data Warga MBI"}</button></div></label>
    {selected && <div className={styles.readonly}><small>Data Master Warga MBI (Read-Only)</small><h3>{selected.name}</h3><p>{selected.maskedNik} · KK {selected.maskedKk} · {selected.kelurahan}, {selected.kecamatan}</p></div>}
    <div className={styles.twoColumns}><label>RT<input name="rt" inputMode="numeric" maxLength={3} defaultValue={selected?.rt === "—" ? "" : selected?.rt} required /></label><label>RW<input name="rw" inputMode="numeric" maxLength={3} defaultValue={selected?.rw === "—" ? "" : selected?.rw} required /></label></div>
    <div className={styles.twoColumns}><label>Estimasi Desil Awal<select name="initialDesil" defaultValue={selected?.desil ?? 1}>{[1,2,3,4,5].map((value) => <option key={value} value={value}>Desil {value}{value <= 2 ? " — Prioritas Utama" : value === 3 ? " — Rentan" : " — Mandiri"}</option>)}</select></label><label>Rencana OPD / Program Tujuan<select name="targetProgramId" defaultValue={programs[0]?.id} required>{programs.map((program) => <option key={program.id} value={program.id}>{program.opdCode} — {program.name}</option>)}</select></label></div>
    <label>Alasan Usulan &amp; Catatan Kasi Kesra<textarea name="reason" minLength={20} maxLength={2000} placeholder="Jelaskan kondisi faktual dan kebutuhan warga..." required /></label>
    {(lookupMessage || mutation.message) && <p className={`${styles.notice} ${styles.noticeError}`} role="alert">{lookupMessage || mutation.message}</p>}
  </form></Dialog>;
}

export function SurveyAssignmentDialog({ citizen, close }: { citizen: KecamatanCitizen; close: () => void }) {
  const mutation = useMutationDone(close); const [today] = useState(() => new Date().toISOString().slice(0, 10)); const [due] = useState(() => new Date(Date.now() + 3 * 86400000).toISOString().slice(0, 10));
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); await mutation.run(() => request(`/api/kecamatan/usulan/${citizen.proposalId}/survei`, "POST", { surveyorName: form.get("surveyorName"), dueDate: form.get("dueDate"), instruction: form.get("instruction") })); }
  return <Dialog title={`Penugasan Survei Lapangan — ${citizen.name}`} close={close} footer={<><button className={styles.secondary} onClick={close}>Batal</button><button className={styles.primary} type="submit" form="kc-assign" disabled={mutation.busy}>Kirim Penugasan Survei</button></>}><form id="kc-assign" className={styles.form} onSubmit={submit}><Identity citizen={citizen} /><label>Pilih Petugas Surveyor<input name="surveyorName" defaultValue={`PSM ${citizen.kelurahan}`} minLength={3} maxLength={150} required /></label><label>Batas Waktu Penyelesaian (SLA)<input type="date" name="dueDate" min={today} defaultValue={due} required /></label><label>Catatan &amp; Instruksi Perintah Tugas<textarea name="instruction" defaultValue="Lakukan verifikasi kondisi tempat tinggal, kependudukan, dan kebutuhan intervensi warga." minLength={10} maxLength={2000} required /></label><MutationMessage message={mutation.message} /></form></Dialog>;
}

export function SurveyResultDialog({ citizen, close }: { citizen: KecamatanCitizen; close: () => void }) {
  const mutation = useMutationDone(close); const survey = citizen.survey!;
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); await mutation.run(() => request(`/api/kecamatan/survei/${survey.id}`, "PATCH", { score: Number(form.get("score")), factualDesil: Number(form.get("factualDesil")), notes: form.get("notes") })); }
  return <Dialog title={`Input Hasil Verifikasi Lapangan — ${citizen.name}`} close={close} footer={<><button className={styles.secondary} onClick={close}>Batal</button><button className={styles.primary} type="submit" form="kc-result" disabled={mutation.busy}>Simpan Hasil Survei</button></>}><form id="kc-result" className={styles.form} onSubmit={submit}><Identity citizen={citizen} /><div className={styles.twoColumns}><label>Skor Hasil Asesmen<input name="score" type="number" min={0} max={100} defaultValue={survey.score ?? 70} required /></label><label>Desil Faktual<select name="factualDesil" defaultValue={survey.factualDesil ?? citizen.desil ?? 1}>{[1,2,3,4,5].map((value) => <option key={value} value={value}>Desil {value}</option>)}</select></label></div><label>Catatan Faktual Surveyor<textarea name="notes" defaultValue={survey.notes} minLength={20} maxLength={3000} placeholder="Tuliskan kondisi lapangan dan rekomendasi tindak lanjut..." required /></label><MutationMessage message={mutation.message} /></form></Dialog>;
}

export function SurveyReviewDialog({ citizen, programs, close }: { citizen: KecamatanCitizen; programs: KecamatanProgram[]; close: () => void }) {
  const mutation = useMutationDone(close); const survey = citizen.survey!;
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const submitter = (event.nativeEvent as SubmitEvent).submitter as HTMLButtonElement | null; const decision = submitter?.value === "REPEAT" ? "REPEAT" : "APPROVE"; await mutation.run(() => request(`/api/kecamatan/survei/${survey.id}/review`, "POST", { decision, targetProgramId: form.get("targetProgramId"), reviewNote: form.get("reviewNote") })); }
  return <Dialog title={`Review Hasil Verifikasi Lapangan — ${citizen.name}`} close={close} footer={<><button className={styles.warning} type="submit" form="kc-review" value="REPEAT" disabled={mutation.busy}>Minta Survei Ulang</button><button className={styles.primary} type="submit" form="kc-review" value="APPROVE" disabled={mutation.busy}><CheckCircle2 size={16} /> Setujui Hasil Verifikasi</button></>}><form id="kc-review" className={styles.form} onSubmit={submit}><Identity citizen={citizen} /><div className={styles.profileGrid}><div><small>Petugas Surveyor</small><strong>{survey.surveyor}</strong></div><div><small>Hasil Asesmen</small><strong>{survey.score}/100 · Desil {survey.factualDesil}</strong></div></div><div className={styles.readonly}><small>Catatan Faktual</small><p>{survey.notes}</p></div><label>Rencana OPD / Program Tujuan<select name="targetProgramId" defaultValue={citizen.targetProgramId ?? programs[0]?.id} required>{programs.map((program) => <option key={program.id} value={program.id}>{program.opdCode} — {program.name}</option>)}</select></label><label>Catatan Persetujuan / Survei Ulang<textarea name="reviewNote" minLength={10} maxLength={2000} defaultValue="Hasil verifikasi faktual telah ditinjau dan layak diteruskan ke OPD teknis." required /></label><MutationMessage message={mutation.message} /></form></Dialog>;
}

export function ReferralDialog({ citizen, programs, close }: { citizen: KecamatanCitizen; programs: KecamatanProgram[]; close: () => void }) {
  const mutation = useMutationDone(close); const target = programs.find((program) => program.id === citizen.targetProgramId) ?? programs[0];
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); await mutation.run(() => request(`/api/kecamatan/usulan/${citizen.proposalId}/rujukan`, "POST", { programId: form.get("programId"), category: form.get("category"), instruction: form.get("instruction"), slaHours: Number(form.get("slaHours")) })); }
  return <Dialog title={`Proses Verifikasi Kewilayahan — ${citizen.name}`} close={close} footer={<><button className={styles.secondary} onClick={close}>Batal</button><button className={styles.primary} type="submit" form="kc-referral" disabled={mutation.busy}><Send size={16} /> Kirim Rujukan ke OPD</button></>}><form id="kc-referral" className={styles.form} onSubmit={submit}><Identity citizen={citizen} /><label>Program OPD Tujuan<select name="programId" defaultValue={target?.id} required>{programs.filter((program) => program.id === citizen.targetProgramId).map((program) => <option key={program.id} value={program.id}>{program.opdName} — {program.name}</option>)}</select></label><label>Kategori Layanan<input name="category" defaultValue={target?.category ?? target?.name} minLength={3} maxLength={250} required /></label><div className={styles.twoColumns}><label>SLA Respons (Jam)<input name="slaHours" type="number" min={1} max={720} defaultValue={48} required /></label><label>Status Verifikasi<input value="Terverifikasi Layak" readOnly /></label></div><label>Catatan Hasil Verifikasi Kewilayahan &amp; Rekomendasi<textarea name="instruction" defaultValue={citizen.reason} minLength={10} maxLength={2000} required /></label><MutationMessage message={mutation.message} /></form></Dialog>;
}

export function HelpdeskDialog({ citizens, close }: { citizens: KecamatanCitizen[]; close: () => void }) {
  const mutation = useMutationDone(close);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); await mutation.run(() => request("/api/kecamatan/helpdesk", "POST", { category: form.get("category"), wargaId: form.get("wargaId"), description: form.get("description") })); }
  return <Dialog title="Hubungi Helpdesk Operator MBI" close={close} footer={<><button className={styles.secondary} onClick={close}>Batal</button><button className={styles.primary} type="submit" form="kc-helpdesk" disabled={mutation.busy}><Send size={16} /> Kirim Laporan Kendala</button></>}><form id="kc-helpdesk" className={styles.form} onSubmit={submit}><p className={styles.notice}>PIC Support wilayah tersedia melalui Pusat Data Diskominfo Kota Bandung.</p><label>Kategori Kendala<select name="category"><option>Anomali NIK Ganda / Data Terkunci</option><option>Ketidaksesuaian Wilayah</option><option>Kendala Rujukan OPD</option><option>Kendala Teknis Aplikasi</option></select></label><label>Warga Terkait (Opsional)<select name="wargaId" defaultValue=""><option value="">Tidak terkait warga tertentu</option>{citizens.map((citizen) => <option key={citizen.id} value={citizen.id}>{citizen.name} — {citizen.maskedNik}</option>)}</select></label><label>Deskripsi Kendala &amp; Catatan Operator<textarea name="description" minLength={20} maxLength={2000} placeholder="Jelaskan detail kendala sistem atau ketidaksesuaian data warga..." required /></label><MutationMessage message={mutation.message} /></form></Dialog>;
}

function MutationMessage({ message }: { message: string }) { return message ? <p className={`${styles.notice} ${styles.noticeError}`} role="alert">{message}</p> : null; }
function Identity({ citizen }: { citizen: KecamatanCitizen }) { return <div className={styles.identity}><small>Nama Warga &amp; NIK</small><h3>{citizen.name}</h3><p>{citizen.maskedNik} · Desil {citizen.desil ?? "—"} · {citizen.kelurahan}, Kec. {citizen.kecamatan}</p><StatusBadge status={citizen.proposalStatus} /></div>; }

export function CitizenDrawer({ citizen, close }: { citizen: KecamatanCitizen; close: () => void }) {
  return <Drawer title={`Profil Master Warga — ${citizen.name}`} close={close} footer={<><button className={styles.secondary} onClick={() => window.print()}><Printer size={16} /> Cetak Profil</button><button className={styles.secondary} onClick={close}>Tutup</button></>}><div className={styles.detailStack}><Identity citizen={citizen} /><section className={styles.detailBox}><h3 className={styles.sectionTitle}>Identitas &amp; Domisili</h3><div className={styles.profileGrid}><div><small>Nomor KK</small><strong>{citizen.maskedKk}</strong></div><div><small>Wilayah</small><strong>{citizen.kelurahan}, Kec. {citizen.kecamatan}</strong></div><div><small>RT / RW</small><strong>{citizen.rt} / {citizen.rw}</strong></div><div><small>Pekerjaan &amp; Tanggungan</small><strong>{citizen.pekerjaan} ({citizen.tanggungan} tanggungan)</strong></div></div></section><DocumentGrid citizen={citizen} /><Timeline events={citizen.events} /></div></Drawer>;
}

export function SurveyDrawer({ citizen, close }: { citizen: KecamatanCitizen; close: () => void }) { const survey = citizen.survey!; return <Drawer title={`Detail Verifikasi Lapangan — ${citizen.name}`} close={close} footer={<><button className={styles.secondary} onClick={() => window.print()}><Printer size={16} /> Cetak Berkas</button><button className={styles.secondary} onClick={close}>Tutup</button></>}><div className={styles.detailStack}><Identity citizen={citizen} /><section className={styles.detailBox}><h3 className={styles.sectionTitle}>Hasil Asesmen Faktual</h3><div className={styles.profileGrid}><div><small>Petugas</small><strong>{survey.surveyor}</strong></div><div><small>Skor / Desil</small><strong>{survey.score ?? "—"}/100 · Desil {survey.factualDesil ?? "—"}</strong></div></div><p>{survey.notes || "Hasil survei belum dikirim."}</p></section><DocumentGrid citizen={citizen} /></div></Drawer>; }

export function ReferralDrawer({ citizen, close }: { citizen: KecamatanCitizen; close: () => void }) { const referral = citizen.referral!; const events = useMemo(() => [...citizen.events, ...referral.events], [citizen.events, referral.events]); return <Drawer title={`Detail Pelacakan Rujukan — ${referral.code}`} close={close} footer={<><button className={styles.secondary} onClick={() => window.print()}><Printer size={16} /> Unduh Berkas Rujukan</button><button className={styles.secondary} onClick={close}>Tutup</button></>}><div className={styles.detailStack}><Identity citizen={citizen} /><section className={styles.detailBox}><div className={styles.profileGrid}><div><small>OPD Tujuan</small><strong>{referral.opdName}</strong></div><div><small>Status Respons</small><StatusBadge status={referral.status} /></div><div><small>Program</small><strong>{referral.programName}</strong></div><div><small>SLA Respons</small><strong>{referral.slaHours} jam</strong></div></div><p>{referral.instruction}</p></section><DocumentGrid citizen={citizen} /><Timeline events={events} /></div></Drawer>; }

function DocumentGrid({ citizen }: { citizen: KecamatanCitizen }) { return <section><h3 className={styles.sectionTitle}>Berkas Verifikasi Terlampir</h3><div className={styles.docs}>{citizen.documents.length ? citizen.documents.map((doc) => <div className={styles.doc} key={doc.id}><div><strong><FileText size={15} /> {doc.label}</strong><small>{doc.type.replaceAll("_", " ")}</small></div><span className={styles.badgeGreen}>{doc.status}</span></div>) : <p className={styles.muted}>Belum ada metadata dokumen yang terlampir.</p>}</div></section>; }
function Timeline({ events }: { events: KecamatanCitizen["events"] }) { return <section><h3 className={styles.sectionTitle}>Riwayat Kewilayahan &amp; Rujukan</h3><div className={styles.timeline}>{events.length ? events.map((event) => <div key={event.id}><span className={styles.muted}>{event.date}</span><p><strong>{event.title}</strong><br /><small>{event.note}</small></p></div>) : <p className={styles.muted}>Belum ada riwayat workflow.</p>}</div></section>; }

export function ActionIcon() { return <Eye size={16} />; }
