"use client";

import { CheckCircle2, ChevronLeft, ChevronRight, Eye, Plus, Users } from "lucide-react";
import type { ReactNode } from "react";
import { useMemo, useState } from "react";

import { AssignSurveyDialog, ProposalDialog, ProposalDrawer, SendDialog, StatusBadge, SurveyDialog } from "@/components/kelurahan/shared/workflow-panels";
import type { KelurahanData, KelurahanProposal } from "@/lib/kelurahan/data";
import styles from "@/components/kelurahan/shared/kelurahan-ui.module.css";

type Mode="new"|"assign"|"survey"|"send"|"detail"|null;
function next(row:KelurahanProposal):{label:string;mode:Exclude<Mode,"new"|null>} {if(row.status==="MENUNGGU_VERIFIKASI_RT_RW")return{label:"Proses",mode:"assign"};if(row.status==="SURVEI_LAPANGAN")return{label:"Isi Survei",mode:"survey"};if(row.status==="SIAP_DIKIRIM_KECAMATAN")return{label:"Kirim ke Kecamatan",mode:"send"};return{label:"Detail",mode:"detail"};}
export function KelurahanUsulan({data}:{data:KelurahanData}){
  const[mode,setMode]=useState<Mode>(null);const[selected,setSelected]=useState<KelurahanProposal|null>(null);const[search,setSearch]=useState("");const[stage,setStage]=useState("");const[rw,setRw]=useState("");
  const rows=useMemo(()=>data.proposals.filter((row)=>!search||`${row.name} ${row.maskedNik}`.toLowerCase().includes(search.toLowerCase())).filter((row)=>!stage||row.status===stage).filter((row)=>!rw||row.rw===rw),[data.proposals,search,stage,rw]);const rwOptions=[...new Set(data.proposals.map((row)=>row.rw))].sort();
  const waiting=data.proposals.filter((row)=>row.status==="MENUNGGU_VERIFIKASI_RT_RW"||row.status==="SURVEI_LAPANGAN").length;const sent=data.proposals.filter((row)=>row.status==="TERKIRIM_KECAMATAN").length;function open(row:KelurahanProposal,nextMode:Exclude<Mode,"new"|null>){setSelected(row);setMode(nextMode);}function close(){setSelected(null);setMode(null);}
  return <section aria-labelledby="kel-usulan-title"><div className={styles.pageHeading}><div><h1 id="kel-usulan-title">Usulan Warga Kelurahan {data.actor.village}</h1><p>Pengelolaan daftar usulan warga rentan baru hasil pendataan RT/RW dan PSM Kelurahan {data.actor.village}.</p></div><button className={styles.primary} onClick={()=>setMode("new")}><Plus size={17}/>Tambah Usulan Warga</button></div>
    <div className={styles.summaryGrid}><Summary label="Total Usulan Bulan Ini" value={data.proposals.length} suffix="Warga" icon={<Users/>}/><Summary label="Menunggu Verifikasi RT/RW" value={waiting} suffix="Usulan" icon={<span>◷</span>}/><Summary label="Disetujui & Dikirim Kecamatan" value={sent} suffix="Usulan" icon={<CheckCircle2/>}/></div>
    <section className={styles.card}><div className={styles.filters}><div className={styles.filterControls}><input className={styles.searchBox} aria-label="Cari usulan" placeholder="NIK atau Nama..." value={search} onChange={(event)=>setSearch(event.target.value)}/></div><div className={styles.filterControls}><select aria-label="Filter tahap" value={stage} onChange={(event)=>setStage(event.target.value)}><option value="">Semua Tahap</option><option value="MENUNGGU_VERIFIKASI_RT_RW">Verifikasi RT/RW</option><option value="SURVEI_LAPANGAN">Survei Lapangan</option><option value="SIAP_DIKIRIM_KECAMATAN">Siap Dikirim</option><option value="TERKIRIM_KECAMATAN">Terkirim Kecamatan</option></select><select aria-label="Filter RW" value={rw} onChange={(event)=>setRw(event.target.value)}><option value="">Semua RW</option>{rwOptions.map((value)=><option key={value} value={value}>RW {value}</option>)}</select></div></div>
      <div className={styles.desktopTable}><table><thead><tr><th>NIK &amp; Nama Warga</th><th>RW / RT</th><th>Kategori Bantuan</th><th>Status Usulan</th><th>Tgl Usulan</th><th>Aksi</th></tr></thead><tbody>{rows.map((row)=>{const action=next(row);return <tr key={row.id}><td><strong>{row.name}</strong><span className={styles.muted}>{row.maskedNik}</span></td><td><strong>RW {row.rw} / RT {row.rt}</strong></td><td><span className={`${styles.badge} ${styles.statusBlue}`}>{row.category}</span></td><td><StatusBadge status={row.status}/></td><td>{row.createdAt}</td><td><button className={`${styles.action} ${action.mode!=="detail"?styles.actionPrimary:""}`} onClick={()=>open(row,action.mode)}>{action.mode==="detail"&&<Eye size={16}/>} {action.label}</button></td></tr>;})}</tbody></table></div><div className={styles.mobileCards}>{rows.map((row)=>{const action=next(row);return <article key={row.id}><header><div><h3>{row.name}</h3><span className={styles.muted}>{row.maskedNik}</span></div><StatusBadge status={row.status}/></header><p>{row.category}</p><button className={`${styles.action} ${styles.actionPrimary}`} onClick={()=>open(row,action.mode)}>{action.label}</button></article>;})}</div>{!rows.length&&<p className={styles.emptyState}>Belum ada usulan yang sesuai filter.</p>}<nav className={styles.pagination}><p>Menampilkan 1–{rows.length} dari {data.proposals.length} antrian</p><div className={styles.pages}><span><ChevronLeft size={15}/></span><strong>1</strong><span>2</span><span>3</span><span>…</span><span><ChevronRight size={15}/></span></div></nav></section>
    {mode==="new"&&<ProposalDialog data={data} close={close}/>} {selected&&mode==="assign"&&<AssignSurveyDialog proposal={selected} data={data} close={close}/>} {selected&&mode==="survey"&&<SurveyDialog proposal={selected} close={close}/>} {selected&&mode==="send"&&<SendDialog proposal={selected} data={data} close={close}/>} {selected&&mode==="detail"&&<ProposalDrawer proposal={selected} data={data} close={close}/>}</section>;
}
function Summary({label,value,suffix,icon}:{label:string;value:number;suffix:string;icon:ReactNode}){return <article className={styles.summaryCard}><div><p>{label}</p><strong>{value} <em>{suffix}</em></strong></div><span className={styles.summaryIcon}>{icon}</span></article>;}
