import Link from "next/link";
import { notFound } from "next/navigation";

import { CaseHero } from "@/components/dinsos/case-hero";
import { CaseTabs } from "@/components/dinsos/case-tabs";
import { requireDinsosActor } from "@/lib/auth/require-dinsos-actor";
import { getDinsosCaseById } from "@/lib/dinsos/cases";
import styles from "@/components/dinsos/case.module.css";

const displayDate=(value:string|null)=>value?new Intl.DateTimeFormat("id-ID",{day:"2-digit",month:"long",year:"numeric",timeZone:"Asia/Jakarta"}).format(new Date(`${value}T00:00:00+07:00`)):"—";
export default async function CaseDataPage({params}:{params:Promise<{caseId:string}>}){const {caseId}=await params;const actor=await requireDinsosActor();const item=await getDinsosCaseById(caseId,actor.profileId);if(!item)notFound();const assessmentReady=item.assessment?.status==="COMPLETED";const resultReady=item.result?.status==="CONFIRMED";return <section>
  <div className={styles.breadcrumb}><span>Antrian Kerja Harian &nbsp;/&nbsp; <strong>Data Warga</strong></span><Link className={styles.back} href="/dinsos">← Kembali ke Antrian</Link></div>
  <CaseHero item={item}/><CaseTabs caseId={caseId} active="data" assessmentReady={assessmentReady} resultReady={resultReady}/>
  {!item.locationResolved&&<p className={styles.warning}>⚠ Wilayah belum terhubung ke master wilayah.</p>}
  <div className={styles.infoGrid}><article className={styles.card}><h2>▣ Identitas Pribadi</h2><div className={styles.fields}><div><span className={styles.label}>Nama Lengkap</span><p className={styles.value}>{item.warga.nama}</p></div><div><span className={styles.label}>NIK</span><p className={styles.value}>{item.warga.maskedNik}</p></div><div><span className={styles.label}>Tempat, Tanggal Lahir</span><p className={styles.value}>{item.warga.tempatLahir??"—"}, {displayDate(item.warga.tanggalLahir)}</p></div><div><span className={styles.label}>Jenis Kelamin</span><p className={styles.value}>{item.warga.jenisKelamin??"—"}</p></div><div><span className={styles.label}>Status Perkawinan</span><p className={styles.value}>{item.warga.statusPerkawinan??"—"}</p></div><div><span className={styles.label}>Nomor Telepon</span><p className={styles.value}>{item.warga.maskedPhone}</p></div></div></article>
  <article className={styles.card}><h2>⌂ Alamat Tempat Tinggal</h2><div className={styles.fields}><div className={styles.full}><span className={styles.label}>Alamat Lengkap</span><p className={styles.value}>{item.warga.alamat??"—"}</p></div><div><span className={styles.label}>RT / RW</span><p className={styles.value}>—</p></div><div><span className={styles.label}>Patokan</span><p className={styles.value}>—</p></div><div><span className={styles.label}>Kelurahan</span><p className={styles.value}>{item.warga.kelurahan??"—"}</p></div><div><span className={styles.label}>Kecamatan</span><p className={styles.value}>{item.warga.kecamatan??"—"}</p></div></div></article>
  <article className={`${styles.card} ${styles.socialCard}`}><h2>▥ Data Sosial Ekonomi Dasar</h2><div className={styles.socialFields}><div><span className={styles.label}>Pendidikan Terakhir</span><p className={styles.value}>{item.warga.pendidikan??"—"}</p></div><div><span className={styles.label}>Pekerjaan Utama</span><p className={styles.value}>{item.warga.pekerjaan??"—"}</p></div><div><span className={styles.label}>Jumlah Anggota KK</span><p className={styles.value}>{item.warga.jumlahAnggotaKk??"—"}</p></div><div><span className={styles.label}>Status Kepemilikan Rumah</span><p className={styles.value}>{item.warga.statusRumah??"—"}</p></div></div></article></div>
  <article className={`${styles.card} ${styles.documents}`}><h2>Dokumen Pendukung</h2><div className={styles.documentList}>{([['ktp','KTP',item.verification?.documents.ktp],['kk','Kartu Keluarga',item.verification?.documents.kk],['rumah','Foto Rumah',item.verification?.documents.rumah],['kondisi-rumah','Kondisi Rumah',item.verification?.documents.kondisiRumah]] as const).map(([type,label,available])=><div className={styles.document} key={type}><strong>{label}</strong><p>{available?<a href={`/api/dinsos/cases/${caseId}/documents/${type}`} target="_blank">Lihat dokumen</a>:"Dokumen belum tersedia"}</p></div>)}</div>{item.verification&&<p className={styles.verifyFooter}>Diverifikasi oleh {item.verification.petugas??"—"} pada {displayDate(item.verification.tanggal)}</p>}</article>
  </section>}
