"use client";

import { Check, Download, Eye, FileImage, FileText, LockKeyhole, Send, ShieldCheck, X } from "lucide-react";
import { useRouter } from "next/navigation";
import type { FormEvent } from "react";
import { useState } from "react";

import type { KelurahanData, KelurahanProposal } from "@/lib/kelurahan/data";
import styles from "./kelurahan-ui.module.css";

type Lookup={id:string;name:string;maskedNik:string;maskedKk:string;village:string};
type Close={close:()=>void};

async function json(pending:Response|Promise<Response>){const response=await pending;const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.message??"Permintaan tidak dapat diproses.");return payload;}
function useMutation(close:()=>void){const router=useRouter();const [busy,setBusy]=useState(false);const [error,setError]=useState("");async function run(action:()=>Promise<unknown>){setBusy(true);setError("");try{await action();close();router.refresh();}catch(cause){setError(cause instanceof Error?cause.message:"Permintaan tidak dapat diproses.");}finally{setBusy(false);}}return{busy,error,run};}

export function StatusBadge({status}:{status:string}){
  const labels:Record<string,string>={MENUNGGU_VERIFIKASI_RT_RW:"Verifikasi RT/RW",SURVEI_LAPANGAN:"Survei Lapangan",SIAP_DIKIRIM_KECAMATAN:"Siap Dikirim ke Kecamatan",TERKIRIM_KECAMATAN:"Terkirim Kecamatan",DITOLAK:"Ditolak"};
  const tone=status==="TERKIRIM_KECAMATAN"?styles.badgeGreen:status==="SIAP_DIKIRIM_KECAMATAN"?styles.statusBlue:status==="SURVEI_LAPANGAN"?styles.statusOrange:status==="DITOLAK"?styles.statusRed:styles.statusBlue;
  return <span className={`${styles.badge} ${tone}`}>{labels[status]??status.replaceAll("_"," ")}</span>;
}

export function ProposalDialog({data,close}:{data:KelurahanData}&Close){
  const [nik,setNik]=useState("");const [lookup,setLookup]=useState<Lookup|null>(null);const [checking,setChecking]=useState(false);const [lookupError,setLookupError]=useState("");
  const [rt,setRt]=useState("04");const [rw,setRw]=useState("08");const [desil,setDesil]=useState("1");const [programId,setProgramId]=useState(data.programs[0]?.id??"");const [reason,setReason]=useState("");
  const mutation=useMutation(close);
  async function check(){setChecking(true);setLookupError("");setLookup(null);try{const result=await json(await fetch("/api/kelurahan/warga/lookup",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({nik})}));setLookup(result.citizen);}catch(cause){setLookupError(cause instanceof Error?cause.message:"NIK tidak ditemukan.");}finally{setChecking(false);}}
  function submit(event:FormEvent){event.preventDefault();if(!lookup){setLookupError("Periksa NIK terlebih dahulu.");return;}void mutation.run(()=>json(fetch("/api/kelurahan/usulan",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({citizenId:lookup.id,rt,rw,estimatedDesil:Number(desil),targetProgramId:programId,reason})})));}
  return <div className={styles.overlay} role="presentation"><section className={styles.dialog} role="dialog" aria-modal="true" aria-labelledby="add-proposal-title"><header><div><h2 id="add-proposal-title">Tambah Usulan Warga Baru — Kelurahan {data.actor.village}</h2><p className={styles.dialogSubtitle}>Input data kependudukan dan lokasi domisili warga untuk pengusulan bantuan di tingkat Kelurahan.</p></div><button type="button" aria-label="Tutup" onClick={close}><X/></button></header><form className={styles.dialogBody} id="proposal-form" onSubmit={submit}><div className={styles.form}>
    <label><strong>Nomor Induk Kependudukan (NIK)</strong><span className={styles.inlineLookup}><input inputMode="numeric" maxLength={16} value={nik} onChange={(event)=>{setNik(event.target.value.replace(/\D/gu,""));setLookup(null);}} placeholder="Wajib 16 digit"/><button type="button" className={styles.primary} onClick={check} disabled={checking||nik.length!==16}><ShieldCheck size={16}/>{checking?"Memeriksa...":"Cek Disdukcapil"}</button></span></label>
    {lookup&&<><p className={styles.notice}>Data NIK valid pada wilayah akun.</p><section className={styles.verified}><h3><LockKeyhole size={15}/> Data terverifikasi Disdukcapil (read-only)</h3><div className={styles.twoColumns}><label>Nama Lengkap<input value={lookup.name} readOnly/></label><label>Nomor Kartu Keluarga (KK)<input value={lookup.maskedKk} readOnly/></label></div></section></>}{lookupError&&<p className={`${styles.notice} ${styles.noticeError}`}>{lookupError}</p>}
    <div className={styles.twoColumns}><label><strong>Kelurahan Domisili</strong><input value={data.actor.village} readOnly/></label><label><strong>RT / RW</strong><span className={styles.inlineFields}><input aria-label="RT" value={rt} onChange={(event)=>setRt(event.target.value.replace(/\D/gu,""))}/><input aria-label="RW" value={rw} onChange={(event)=>setRw(event.target.value.replace(/\D/gu,""))}/></span></label></div>
    <div className={styles.twoColumns}><label><strong>Estimasi Desil Awal</strong><select value={desil} onChange={(event)=>setDesil(event.target.value)}>{[1,2,3,4,5].map((value)=><option key={value} value={value}>Desil {value}{value===1?" — Prioritas Utama":""}</option>)}</select></label><label><strong>Rencana OPD Tujuan</strong><select value={programId} onChange={(event)=>setProgramId(event.target.value)}>{data.programs.map((program)=><option key={program.id} value={program.id}>{program.opdName} — {program.name}</option>)}</select></label></div>
    <label><strong>Alasan Usulan &amp; Catatan Faktual</strong><textarea value={reason} onChange={(event)=>setReason(event.target.value)} placeholder="Jelaskan kondisi warga dan kebutuhan intervensi..."/></label>{mutation.error&&<p className={`${styles.notice} ${styles.noticeError}`}>{mutation.error}</p>}
  </div></form><footer><button type="button" className={styles.secondary} onClick={close}>Batal</button><button form="proposal-form" className={styles.primary} disabled={mutation.busy||!lookup||!programId}><Send size={16}/>{mutation.busy?"Menyimpan...":"Simpan & Penugasan Survei Kelurahan"}</button></footer></section></div>;
}

export function AssignSurveyDialog({proposal,data,close}:{proposal:KelurahanProposal;data:KelurahanData}&Close){
  const initial=data.surveyors[0];const [surveyorId,setSurveyorId]=useState(initial?.id??"");const [instruction,setInstruction]=useState("Lakukan verifikasi faktual kondisi fisik rumah, status pekerjaan kepala keluarga, dan verifikasi kelayakan usulan MBI.");const mutation=useMutation(close);
  function submit(event:FormEvent){event.preventDefault();const selected=data.surveyors.find((row)=>row.id===surveyorId);void mutation.run(()=>json(fetch(`/api/kelurahan/usulan/${proposal.id}/assign-survey`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({surveyorProfileId:selected?.id??null,surveyorName:selected?.name??data.actor.name,instruction,expectedVersion:proposal.version})})));}
  return <div className={styles.overlay}><section className={styles.dialog} role="dialog" aria-modal="true" aria-labelledby="assign-title"><header><div><h2 id="assign-title">Proses Verifikasi Kelurahan — {proposal.name}</h2><p className={styles.dialogSubtitle}>Tinjau bukti faktual sebelum memberikan persetujuan rujukan.</p></div><button type="button" aria-label="Tutup" onClick={close}><X/></button></header><form id="assign-form" className={styles.dialogBody} onSubmit={submit}><div className={styles.form}><section className={styles.verified}><h3><LockKeyhole size={15}/> Data terverifikasi Disdukcapil (read-only)</h3><div className={styles.twoColumns}><label>Nama Lengkap<input value={proposal.name} readOnly/></label><label>Nomor Kartu Keluarga (KK)<input value={proposal.maskedKk} readOnly/></label></div><div className={styles.verificationFooter}><span>Petugas: {data.actor.name}</span><StatusBadge status={proposal.status}/></div></section><div className={styles.twoColumns}><label><strong>Kelurahan Domisili</strong><input value={`${data.actor.village} (RT ${proposal.rt} / RW ${proposal.rw})`} readOnly/></label><label><strong>Petugas Surveyer Lapangan</strong><select value={surveyorId} onChange={(event)=>setSurveyorId(event.target.value)}>{data.surveyors.map((row)=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label></div><label><strong>Catatan Perintah Tugas &amp; Instruksi Survei</strong><textarea value={instruction} onChange={(event)=>setInstruction(event.target.value)}/></label><div className={styles.attachment}><FileText/><span><strong>Form_Pengantar_RT{proposal.rt}_RW{proposal.rw}.pdf</strong><small>Dokumen verifikasi</small></span><button type="button">Lihat</button></div>{mutation.error&&<p className={`${styles.notice} ${styles.noticeError}`}>{mutation.error}</p>}</div></form><footer><button type="button" className={styles.secondary} onClick={close}>Batal</button><button form="assign-form" className={styles.primary} disabled={mutation.busy}><ClipboardIcon/>{mutation.busy?"Menyimpan...":"Simpan & Tugaskan Surveyor"}</button></footer></section></div>;
}

function ClipboardIcon(){return <FileText size={16}/>;}

export function SurveyDialog({proposal,close}:{proposal:KelurahanProposal}&Close){
  const [score,setScore]=useState("84");const [desil,setDesil]=useState(String(proposal.estimatedDesil));const [notes,setNotes]=useState("Verifikasi faktual PSM telah dilakukan. Kondisi fisik, dokumen keluarga, dan kelayakan program sesuai dengan hasil survei lapangan.");const mutation=useMutation(close);
  function submit(event:FormEvent){event.preventDefault();if(!proposal.survey)return;void mutation.run(()=>json(fetch(`/api/kelurahan/survei/${proposal.survey!.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({score:Number(score),factualDesil:Number(desil),notes,expectedVersion:proposal.version})})));}
  return <div className={styles.overlay}><section className={styles.dialog} role="dialog" aria-modal="true" aria-labelledby="survey-title"><header><div><h2 id="survey-title">Hasil Survei Lapangan — {proposal.name}</h2><p className={styles.dialogSubtitle}>Catat hasil verifikasi faktual PSM sebelum usulan dikirim ke Kecamatan.</p></div><button type="button" aria-label="Tutup" onClick={close}><X/></button></header><form id="survey-form" className={styles.dialogBody} onSubmit={submit}><div className={styles.form}><section className={styles.identity}><small>Warga &amp; Lokasi</small><h3>{proposal.name}</h3><p>{proposal.maskedNik} · RT {proposal.rt} / RW {proposal.rw}</p><StatusBadge status={proposal.status}/></section><div className={styles.twoColumns}><label><strong>Skor Asesmen Faktual</strong><input type="number" min={0} max={100} value={score} onChange={(event)=>setScore(event.target.value)}/></label><label><strong>Desil Faktual</strong><select value={desil} onChange={(event)=>setDesil(event.target.value)}>{[1,2,3,4,5].map((value)=><option key={value} value={value}>Desil {value}</option>)}</select></label></div><label><strong>Hasil Survei &amp; Catatan Lapangan</strong><textarea value={notes} onChange={(event)=>setNotes(event.target.value)}/></label>{mutation.error&&<p className={`${styles.notice} ${styles.noticeError}`}>{mutation.error}</p>}</div></form><footer><button type="button" className={styles.secondary} onClick={close}>Batal</button><button form="survey-form" className={styles.primary} disabled={mutation.busy}><Check size={16}/>{mutation.busy?"Menyimpan...":"Simpan Hasil Verifikasi"}</button></footer></section></div>;
}

export function SendDialog({proposal,data,close}:{proposal:KelurahanProposal;data:KelurahanData}&Close){
  const [note,setNote]=useState("Usulan prioritas terindikasi membutuhkan penanganan cepat. Berkas verifikasi Kelurahan dan hasil survei faktual PSM telah lengkap.");const mutation=useMutation(close);
  function submit(event:FormEvent){event.preventDefault();void mutation.run(()=>json(fetch(`/api/kelurahan/usulan/${proposal.id}/send`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({note,expectedVersion:proposal.version})})));}
  return <div className={styles.overlay}><section className={styles.dialog} role="dialog" aria-modal="true" aria-labelledby="send-title"><header><div><h2 id="send-title">Kirim Usulan Warga ke Kecamatan — {proposal.name}</h2><p className={styles.dialogSubtitle}>Tinjau kelengkapan berkas sebelum mengirimkan usulan resmi ke Kecamatan {data.actor.district}.</p></div><button type="button" aria-label="Tutup" onClick={close}><X/></button></header><form id="send-form" className={styles.dialogBody} onSubmit={submit}><div className={styles.form}><section className={styles.verified}><h3><LockKeyhole size={15}/> Data terverifikasi &amp; hasil survei lapangan (read-only)</h3><div className={styles.twoColumns}><label>Nama Lengkap<input value={proposal.name} readOnly/></label><label>Nomor Kartu Keluarga (KK)<input value={proposal.maskedKk} readOnly/></label></div><div className={styles.verificationFooter}><span>Petugas: {proposal.survey?.surveyor}</span><span className={`${styles.badge} ${styles.statusRed}`}>Skor: {proposal.survey?.score}/100 (Desil {proposal.survey?.factualDesil})</span></div></section><div className={styles.twoColumns}><label><strong>Kelurahan Domisili</strong><input value={`${data.actor.village} (RT ${proposal.rt} / RW ${proposal.rw})`} readOnly/></label><label><strong>Rencana OPD Tujuan</strong><input value={`${proposal.targetOpd} — ${proposal.targetProgram}`} readOnly/></label></div><label><strong>Catatan Pengantar Kasi Kesra Kelurahan</strong><textarea value={note} onChange={(event)=>setNote(event.target.value)}/></label><div className={styles.attachment}><FileText/><span><strong>Form_Asesmen_Faktual_PSM_{data.actor.village}.pdf</strong><small>Berkas hasil survei</small></span><button type="button">Lihat</button></div>{mutation.error&&<p className={`${styles.notice} ${styles.noticeError}`}>{mutation.error}</p>}</div></form><footer><button type="button" className={styles.secondary} onClick={close}>Batal</button><button form="send-form" className={styles.primary} disabled={mutation.busy}><Send size={16}/>{mutation.busy?"Mengirim...":"Kirim Usulan ke Kecamatan"}</button></footer></section></div>;
}

export function ProposalDrawer({proposal,data,close}:{proposal:KelurahanProposal;data:KelurahanData}&Close){
  return <div className={styles.drawerOverlay}><aside className={styles.drawer} role="dialog" aria-modal="true" aria-labelledby="proposal-detail-title"><header><h2 id="proposal-detail-title"><FileText size={19}/> Detail Usulan Warga — USL-KEL-{proposal.id.slice(0,8).toUpperCase()}</h2><button type="button" aria-label="Tutup" onClick={close}><X/></button></header><div className={styles.drawerBody}><div className={styles.detailStack}><section className={styles.identity}><small>Nama Warga &amp; NIK</small><h3>{proposal.name} <span className={styles.muted}>({proposal.maskedNik})</span></h3><p>RW {proposal.rw} / RT {proposal.rt} {data.actor.village}, Kec. {data.actor.district}</p><StatusBadge status={proposal.status}/></section><section className={styles.handoffBox}><StatusBadge status={proposal.status}/><div className={styles.twoColumns}><div><small>Target OPD</small><strong>{proposal.targetOpd}</strong></div><div><small>Kategori Layanan</small><strong>{proposal.category}</strong></div></div></section><div><h3 className={styles.sectionTitle}>Berkas Verifikasi Terlampir</h3><div className={styles.docs}>{proposal.documents.map((doc)=>{const Icon=doc.type==="FOTO_LAPANGAN"?FileImage:FileText;return <article className={styles.doc} key={doc.id}><Icon size={20}/><div><strong>{doc.label}</strong><small>{doc.status.replaceAll("_"," ")}</small></div><button type="button" className={styles.tableLink}><Eye size={15}/> Pratinjau</button></article>;})}</div></div><section><h3 className={styles.sectionTitle}>Riwayat Verifikasi Kelurahan</h3><div className={styles.timeline}>{proposal.events.map((event,index)=><div key={event.id}><strong>{event.title}</strong><small>{event.date}{index===proposal.events.length-1?" · 10:30 WIB":""}</small><p>{event.note}</p></div>)}</div></section></div></div><footer><button type="button" className={styles.secondary}><Download size={16}/> Unduh Berkas Usulan (PDF)</button><button type="button" className={styles.secondary} onClick={close}>Tutup</button></footer></aside></div>;
}
