"use client";

import { ChevronLeft, ChevronRight, CircleCheckBig, GraduationCap, Printer, TriangleAlert } from "lucide-react";
import { useMemo, useState } from "react";
import { Dialog, Drawer } from "@/components/disdik/shared/dialog";
import styles from "@/components/disdik/shared/disdik-ui.module.css";
import type { DisdikDocumentStatus, DisdikProgram, DisdikReferral, DisdikReferralStatus, DisdikSchool } from "@/lib/disdik/data";

type Mode = "start" | "progress" | "detail" | null;
function label(status: DisdikReferralStatus) { if (status === "PERLU_DIPROSES") return "Perlu Diproses"; if (status === "DALAM_PROSES") return "Sedang Diverifikasi"; return "Terintervensi / Selesai"; }
function StatusBadge({ status }: { status: DisdikReferralStatus }) { return <span className={`${styles.badge} ${status === "PERLU_DIPROSES" ? styles.badgeAmber : status === "SELESAI" ? styles.badgeGreen : ""}`}>{label(status)}</span>; }
function rupiah(value: number | null) { return value === null ? "—" : new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 }).format(value); }

export function DisdikDashboard({ initialReferrals, programs, schools, summary, preview }: { initialReferrals: DisdikReferral[]; programs: DisdikProgram[]; schools: DisdikSchool[]; summary: { newReferrals: number; processing: number; completed: number }; preview: boolean }) {
  const [referrals, setReferrals] = useState(initialReferrals); const [selected, setSelected] = useState<DisdikReferral | null>(null); const [mode, setMode] = useState<Mode>(null); const [statusFilter, setStatusFilter] = useState(""); const [levelFilter, setLevelFilter] = useState(""); const [notice, setNotice] = useState(""); const [complete, setComplete] = useState(false);
  const filtered = useMemo(() => referrals.filter((item) => (!statusFilter || item.status === statusFilter) && (!levelFilter || item.level.includes(levelFilter))), [referrals, statusFilter, levelFilter]);
  const today = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Jakarta", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date());
  function open(item: DisdikReferral, next: Exclude<Mode, null>) { setSelected(item); setMode(next); setNotice(""); setComplete(false); }
  function close() { setSelected(null); setMode(null); setNotice(""); setComplete(false); }
  async function api(url: string, init: RequestInit) { if (preview) return { ok: true, json: async () => ({ interventionId: crypto.randomUUID() }) }; return fetch(url, init); }

  async function submitStart(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!selected) return; const form = new FormData(event.currentTarget); const response = await api(`/api/disdik/referrals/${selected.id}/start`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ programId: form.get("programId"), schoolId: form.get("schoolId"), studentLevel: form.get("studentLevel"), aidItem: form.get("aidItem"), startDate: form.get("startDate"), actionPlan: form.get("actionPlan") }) }); const body = await response.json().catch(() => ({})); if (!response.ok) return setNotice(body.error ?? "Intervensi tidak dapat dimulai."); const program = programs.find((item) => item.id === form.get("programId")); const school = schools.find((item) => item.id === form.get("schoolId"));
    setReferrals((items) => items.map((item) => item.id === selected.id ? { ...item, interventionId: body.interventionId, status: "DALAM_PROSES", aidStatus: "VERIFIKASI", documentStatus: "MENUNGGU", progress: 0, programId: program?.id ?? item.programId, program: program?.name ?? item.program, schoolId: school?.id ?? item.schoolId, school: school?.name ?? item.school, level: String(form.get("studentLevel")), aidItem: String(form.get("aidItem")), notes: String(form.get("actionPlan")), plannedBudget: program?.budgetPerStudent ?? 0, timeline: [...item.timeline, { id: crypto.randomUUID(), type: "STARTED", date: "Hari ini", note: "Rujukan diterima dan verifikasi pendidikan dimulai.", progress: 0 }] } : item)); setNotice("Intervensi pendidikan dimulai."); window.setTimeout(close, 500);
  }
  async function submitProgress(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!selected?.interventionId) return; const form = new FormData(event.currentTarget); const isComplete = form.get("aidStatus") === "SELESAI"; const payload = isComplete ? { realizedAmount: Number(form.get("realizedAmount")), completionDate: form.get("completionDate"), aidItem: form.get("aidItem"), evaluation: form.get("evaluation") } : { progressPercent: Number(form.get("progressPercent")), documentStatus: form.get("documentStatus"), realizedAmount: Number(form.get("realizedAmount")), evaluation: form.get("evaluation") }; const response = await api(`/api/disdik/interventions/${selected.interventionId}/${isComplete ? "complete" : "progress"}`, { method: isComplete ? "POST" : "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json().catch(() => ({})); if (!response.ok) return setNotice(body.error ?? "Progress tidak dapat disimpan."); const progress = isComplete ? 100 : Number(form.get("progressPercent")); const evaluation = String(form.get("evaluation"));
    setReferrals((items) => items.map((item) => item.id === selected.id ? { ...item, status: isComplete ? "SELESAI" : "DALAM_PROSES", aidStatus: isComplete ? "SELESAI" : "PENYALURAN", documentStatus: isComplete ? "LULUS" : String(form.get("documentStatus")) as DisdikDocumentStatus, progress, realizedAmount: Number(form.get("realizedAmount")), aidItem: isComplete ? String(form.get("aidItem")) : item.aidItem, notes: evaluation, timeline: [...item.timeline, { id: crypto.randomUUID(), type: isComplete ? "COMPLETED" : "PROGRESS_UPDATED", date: "Hari ini", note: evaluation, progress }] } : item)); setNotice(isComplete ? "Intervensi pendidikan selesai." : "Progress intervensi tersimpan."); window.setTimeout(close, 500);
  }
  const current = referrals === initialReferrals ? summary : { newReferrals: referrals.filter((x) => x.status === "PERLU_DIPROSES").length, processing: referrals.filter((x) => x.status === "DALAM_PROSES").length, completed: referrals.filter((x) => x.status === "SELESAI").length };
  return <section aria-labelledby="disdik-title">
    <div className={styles.pageHeading}><div><h1 id="disdik-title">Rujukan Masuk &amp; Intervensi</h1><p>Pengelolaan rujukan bantuan biaya pendidikan, fasilitasi seragam &amp; alat tulis, serta pendampingan beasiswa MBI.</p></div></div>
    <div className={styles.summaryGrid}><article className={styles.summaryCard}><span className={styles.summaryIcon}><TriangleAlert size={27} /></span><div><p>Rujukan Baru<br />(Perlu Tindak Lanjut)</p><strong>{current.newReferrals}</strong></div></article><article className={styles.summaryCard}><span className={styles.summaryIcon}><GraduationCap size={27} /></span><div><p>Dalam Proses Bantuan</p><strong>{current.processing}</strong></div></article><article className={styles.summaryCard}><span className={styles.summaryIcon}><CircleCheckBig size={27} /></span><div><p>Terintervensi Beasiswa / Selesai</p><strong>{current.completed}</strong></div></article></div>
    <section className={styles.card} aria-label="Daftar rujukan masuk">{preview && <p className={styles.previewNote}>Mode pratinjau Disdik aktif untuk pengembangan lokal.</p>}<div className={styles.filters}><h2>Daftar Rujukan Masuk</h2><div className={styles.filterControls}><select aria-label="Filter status" value={statusFilter} onChange={(e) => setStatusFilter(e.target.value)}><option value="">Semua Status</option><option value="PERLU_DIPROSES">Perlu Diproses</option><option value="DALAM_PROSES">Dalam Proses</option><option value="SELESAI">Selesai</option></select><select aria-label="Filter jenjang" value={levelFilter} onChange={(e) => setLevelFilter(e.target.value)}><option value="">Semua Jenjang</option><option>SD</option><option>SMP</option><option>SMA</option><option>Kesetaraan</option></select></div></div>
      <div className={styles.desktopTable}><table><thead><tr><th>ID Rujukan / Warga</th><th>Tanggal</th><th>Jenjang &amp; Kelurahan</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{filtered.map((item) => <tr key={item.id}><td><strong>{item.name}</strong><span className={styles.muted}>{item.maskedNik}<br />{item.code}</span></td><td>{item.date}</td><td>{item.level}<br /><span className={styles.muted}>{item.kelurahan}</span></td><td><StatusBadge status={item.status} /></td><td><button className={`${styles.action} ${item.status === "PERLU_DIPROSES" ? styles.actionPrimary : ""}`} onClick={() => open(item, item.status === "PERLU_DIPROSES" ? "start" : item.status === "DALAM_PROSES" ? "progress" : "detail")}>{item.status === "PERLU_DIPROSES" ? "Proses Intervensi" : item.status === "DALAM_PROSES" ? "Update Progress" : "Detail"}</button></td></tr>)}</tbody></table></div>
      <div className={styles.mobileCards}>{filtered.map((item) => <article key={item.id}><header><div><h3>{item.name}</h3><span className={styles.muted}>{item.maskedNik}<br />{item.code}</span></div><StatusBadge status={item.status} /></header><dl><div><dt>Tanggal</dt><dd>{item.date}</dd></div><div><dt>Jenjang</dt><dd>{item.level}</dd></div></dl><button className={`${styles.action} ${item.status === "PERLU_DIPROSES" ? styles.actionPrimary : ""}`} onClick={() => open(item, item.status === "PERLU_DIPROSES" ? "start" : item.status === "DALAM_PROSES" ? "progress" : "detail")}>{item.status === "PERLU_DIPROSES" ? "Proses Intervensi" : item.status === "DALAM_PROSES" ? "Update Progress" : "Detail"}</button></article>)}</div>
      {!filtered.length && <p className={styles.emptyState}>Belum ada rujukan pendidikan yang sesuai filter.</p>}<nav className={styles.pagination} aria-label="Halaman rujukan"><p>Menampilkan 1–{filtered.length} dari {referrals.length} data</p><div className={styles.pages}><span><ChevronLeft size={15} /></span><strong aria-current="page">1</strong><span><ChevronRight size={15} /></span></div></nav>
    </section>
    {selected && mode === "start" && <Dialog title={`Proses Intervensi Disdik — ${selected.code}`} close={close} footer={<><button className={styles.secondary} onClick={close}>Batal</button><button className={styles.primary} type="submit" form="start-disdik">Simpan &amp; Proses Bantuan</button></>}><form id="start-disdik" className={styles.form} onSubmit={submitStart}><div className={styles.identity}><small>Identitas Siswa / Warga</small><h3>{selected.name}</h3><p>NIK: {selected.maskedNik} | Desil: Desil {selected.desil || "—"} | Kelurahan: {selected.kelurahan}</p><span className={styles.badge}>Bantuan Pendidikan</span></div><label>Pilih Program Intervensi Pendidikan<select name="programId" defaultValue={selected.programId ?? programs.find((x) => x.status === "AKTIF")?.id} required>{programs.filter((x) => x.status === "AKTIF").map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Sekolah Tujuan / Penerima<select name="schoolId" defaultValue={selected.schoolId ?? schools[0]?.id} required>{schools.map((item) => <option key={item.id} value={item.id}>{item.name} — {item.level}</option>)}</select></label><label>Jenjang Siswa<input name="studentLevel" defaultValue={selected.level} minLength={2} maxLength={100} required /></label><label>Jenis Bantuan / Sarana<input name="aidItem" defaultValue={selected.aidItem} minLength={3} maxLength={500} required /></label><label>Tanggal Penyaluran Bantuan<input type="date" name="startDate" defaultValue={today} required /></label><label>Rencana Intervensi &amp; Catatan Rekomendasi<textarea name="actionPlan" defaultValue={selected.notes} minLength={10} maxLength={2000} required /></label>{notice && <p role="status">{notice}</p>}</form></Dialog>}
    {selected && mode === "progress" && <Dialog title={`Update Progress Intervensi — ${selected.code}`} close={close} footer={<><button className={styles.secondary} onClick={close}>Batal</button><button className={styles.primary} type="submit" form="progress-disdik">{complete ? "Simpan & Selesaikan Intervensi" : "Simpan & Update Progress"}</button></>}><form id="progress-disdik" className={styles.form} onSubmit={submitProgress}><div className={styles.identity}><small>Nama Warga</small><h3>{selected.name} ({selected.maskedNik})</h3><p>Desil {selected.desil || "—"} | {selected.kelurahan}<br />{selected.program}</p><span className={styles.badge}>{selected.aidStatus === "PENYALURAN" ? "Dalam Penyaluran" : "Sedang Diverifikasi"}</span></div><label>Status Intervensi Baru<select name="aidStatus" defaultValue="PENYALURAN" onChange={(e) => setComplete(e.target.value === "SELESAI")}><option value="PENYALURAN">Dalam Penyaluran Bantuan / Terintervensi</option><option value="SELESAI">Terintervensi / Selesai</option></select></label>{!complete && <div className={styles.twoColumns}><label>Persentase Progress (%)<input name="progressPercent" type="number" min="1" max="99" defaultValue={selected.progress ?? 50} required /></label><label>Status Verifikasi Dokumen<select name="documentStatus" defaultValue={selected.documentStatus ?? "MENUNGGU"}><option value="MENUNGGU">Dalam Verifikasi</option><option value="LULUS">Lulus Verifikasi &amp; SK Terbit</option><option value="DITOLAK">Dokumen Ditolak</option></select></label></div>}<label>Realisasi Pagu Bantuan (Rp)<input name="realizedAmount" type="number" min="0" max="1000000000000" defaultValue={selected.realizedAmount ?? selected.plannedBudget} required /></label>{complete && <><label>Bantuan / Sarana yang Diterima<input name="aidItem" defaultValue={selected.aidItem} minLength={3} maxLength={500} required /></label><label>Tanggal Selesai Intervensi<input name="completionDate" type="date" defaultValue={today} required /></label></>}<label>Catatan Progress Penyaluran Disdik<textarea name="evaluation" defaultValue={selected.notes} minLength={10} maxLength={2000} required /></label>{notice && <p role="status">{notice}</p>}</form></Dialog>}
    {selected && mode === "detail" && <Drawer title={`Detail Intervensi Pendidikan — ${selected.code}`} close={close} footer={<><button className={styles.secondary} onClick={() => window.print()}><Printer size={16} /> Unduh Rekap (PDF)</button><button className={styles.secondary} onClick={close}>Tutup</button></>}><div className={styles.detailStack}><div className={styles.identity}><small>Nama Warga</small><h3>{selected.name}</h3><p>{selected.maskedNik}<br />Desil {selected.desil || "—"} | {selected.kelurahan}</p><span className={`${styles.badge} ${styles.badgeGreen}`}>Terintervensi / Selesai</span></div><div className={styles.twoColumns}><div className={styles.detailBox}><small>Ringkasan Bantuan Disdik</small><strong>{selected.aidItem}</strong></div><div className={styles.detailBox}><small>Total Pagu Terserap</small><strong>{rupiah(selected.realizedAmount)}</strong></div></div><div className={styles.detailBox}><small>Informasi Lembaga &amp; Keaktifan</small><strong>{selected.school} — {selected.progress === 100 ? "Aktif Pembelajaran" : `${selected.progress ?? 0}% progress`}</strong></div><section><h2>Riwayat Pendampingan Disdik</h2><div className={styles.timeline}>{selected.timeline.map((event) => <div key={event.id}><span className={styles.muted}>{event.date}</span><p>{event.note}</p></div>)}</div></section></div></Drawer>}
  </section>;
}
