import "server-only";

import { maskNik } from "@/lib/privacy/mask-nik";
import { createAdminClient } from "@/lib/supabase/admin";

export type DisdikReferralStatus = "PERLU_DIPROSES" | "DALAM_PROSES" | "SELESAI";
export type DisdikAidStatus = "VERIFIKASI" | "PENYALURAN" | "SELESAI" | "TIDAK_AKTIF";
export type DisdikDocumentStatus = "MENUNGGU" | "LULUS" | "DITOLAK";
export type DisdikTimelineEvent = { id: string; type: "STARTED" | "PROGRESS_UPDATED" | "COMPLETED" | "CANCELLED"; date: string; note: string; progress: number | null };
export type DisdikReferral = { id: string; interventionId: string | null; code: string; name: string; maskedNik: string; date: string; programId: string | null; program: string; schoolId: string | null; school: string; level: string; desil: number; kelurahan: string; status: DisdikReferralStatus; aidStatus: DisdikAidStatus | null; documentStatus: DisdikDocumentStatus | null; plannedBudget: number; realizedAmount: number | null; aidItem: string; notes: string; progress: number | null; timeline: DisdikTimelineEvent[] };
export type DisdikProgram = { id: string; code: string; name: string; level: string; aidType: string; schoolId: string; school: string; duration: string; executionDate: string; budgetPerStudent: number; filled: number; capacity: number; status: "AKTIF" | "PENUH" | "NONAKTIF"; location: string; description: string };
export type DisdikSchool = { id: string; code: string; name: string; level: string; kelurahan: string; address: string };
export type EducationReport = { id: string; referralCode: string; name: string; maskedNik: string; level: string; kelurahan: string; school: string; program: string; aidItem: string; realizedAmount: number; status: "DALAM_PENYALURAN" | "TERINTERVENSI_SELESAI"; disbursementDate: string; notes: string; timeline: DisdikTimelineEvent[] };

export const previewEnabled = process.env.NODE_ENV !== "production" && process.env.DISDIK_PREVIEW_MODE === "true";
function fail(error: { message?: string } | null, context: string) { if (error) throw new Error(`${context}: ${error.message ?? "database error"}`); }
function formatDate(value: string | null) { if (!value) return "—"; return new Intl.DateTimeFormat("id-ID", { day: "2-digit", month: "short", year: "numeric", timeZone: "Asia/Jakarta" }).format(new Date(value)); }

const previewSchools: DisdikSchool[] = [
  { id: "00000000-0000-4000-8000-000000000201", code: "SCH-SMP-12", name: "SMP Negeri 12 Bandung", level: "SMP", kelurahan: "Sukajadi", address: "Kota Bandung" },
  { id: "00000000-0000-4000-8000-000000000202", code: "SCH-SDN-03", name: "SDN 03 Pasteur", level: "SD", kelurahan: "Pasteur", address: "Kota Bandung" },
  { id: "00000000-0000-4000-8000-000000000203", code: "SCH-PKBM-01", name: "PKBM Harapan Bangsa", level: "KESETARAAN", kelurahan: "Sekeloa", address: "Kota Bandung" },
];
const previewPrograms: DisdikProgram[] = [
  { id: "00000000-0000-4000-8000-000000000301", code: "PRG-EDU-01", name: "Beasiswa Rawan Putus Sekolah (RPS) MBI", level: "SD & SMP", aidType: "Beasiswa DSP & Operasional", schoolId: previewSchools[0].id, school: previewSchools[0].name, duration: "3 Bulan", executionDate: "15 Sep 2026", budgetPerStudent: 2500000, filled: 32, capacity: 40, status: "AKTIF", location: "Kota Bandung", description: "Pembebasan biaya operasional sekolah dan bantuan perlengkapan bagi siswa rentan." },
  { id: "00000000-0000-4000-8000-000000000302", code: "PRG-EDU-02", name: "Bantuan Seragam & Alat Tulis", level: "SD", aidType: "Perlengkapan Sekolah", schoolId: previewSchools[1].id, school: previewSchools[1].name, duration: "2 Bulan", executionDate: "01 Mar 2026", budgetPerStudent: 1500000, filled: 20, capacity: 20, status: "PENUH", location: "Pasteur", description: "Pengadaan perlengkapan belajar untuk siswa sekolah dasar." },
  { id: "00000000-0000-4000-8000-000000000303", code: "PRG-EDU-03", name: "Fasilitasi Kejar Paket C", level: "Kesetaraan", aidType: "Modul & Biaya Operasional", schoolId: previewSchools[2].id, school: previewSchools[2].name, duration: "4 Bulan", executionDate: "10 Jan 2026", budgetPerStudent: 4200000, filled: 12, capacity: 15, status: "AKTIF", location: "Sekeloa", description: "Fasilitasi pendidikan kesetaraan Paket C dan modul pembelajaran." },
];
const previewReferrals: DisdikReferral[] = [
  { id: "00000000-0000-4000-8000-000000000401", interventionId: null, code: "REF-EDU-2026-101", name: "Randi Permana", maskedNik: "32730521xxxx9988", date: "14 Feb 2026", programId: previewPrograms[0].id, program: previewPrograms[0].name, schoolId: previewSchools[0].id, school: previewSchools[0].name, level: "SMP (Kelas 8)", desil: 1, kelurahan: "Sukajadi", status: "PERLU_DIPROSES", aidStatus: null, documentStatus: null, plannedBudget: 2500000, realizedAmount: null, aidItem: "Beasiswa DSP & set seragam", notes: "Siswa terancam putus sekolah dan membutuhkan bantuan biaya pendidikan.", progress: null, timeline: [] },
  { id: "00000000-0000-4000-8000-000000000402", interventionId: "00000000-0000-4000-8000-000000000502", code: "REF-EDU-2026-115", name: "Siti Nurhaliza", maskedNik: "32730455xxxx1122", date: "08 Feb 2026", programId: previewPrograms[1].id, program: previewPrograms[1].name, schoolId: previewSchools[1].id, school: previewSchools[1].name, level: "SD (Kelas 4)", desil: 1, kelurahan: "Pasteur", status: "DALAM_PROSES", aidStatus: "PENYALURAN", documentStatus: "LULUS", plannedBudget: 1500000, realizedAmount: 1500000, aidItem: "Set perlengkapan seragam & alat tulis lengkap", notes: "Verifikasi kelayakan tuntas dan bantuan sedang disalurkan.", progress: 75, timeline: [{ id: "e-21", type: "STARTED", date: "08 Feb 2026", note: "Penerimaan rujukan & verifikasi kelayakan bantuan seragam SD", progress: 0 }, { id: "e-22", type: "PROGRESS_UPDATED", date: "01 Mar 2026", note: "Pengadaan & pembagian paket seragam sekolah di SDN 03 Pasteur", progress: 60 }, { id: "e-23", type: "PROGRESS_UPDATED", date: "15 Apr 2026", note: "Penandatanganan BAST bantuan oleh kepala sekolah & orang tua siswa", progress: 75 }] },
  { id: "00000000-0000-4000-8000-000000000403", interventionId: "00000000-0000-4000-8000-000000000503", code: "REF-EDU-2026-078", name: "Rian Hidayat", maskedNik: "32731012xxxx3344", date: "22 Jan 2026", programId: previewPrograms[2].id, program: previewPrograms[2].name, schoolId: previewSchools[2].id, school: previewSchools[2].name, level: "SMA / Kejar Paket C", desil: 1, kelurahan: "Sekeloa", status: "SELESAI", aidStatus: "SELESAI", documentStatus: "LULUS", plannedBudget: 4200000, realizedAmount: 4200000, aidItem: "Set kit pembelajaran & modul Paket C", notes: "Peserta resmi aktif dalam pembelajaran kesetaraan.", progress: 100, timeline: [{ id: "e-31", type: "STARTED", date: "10 Jan 2026", note: "Penerimaan rujukan & verifikasi data anak putus sekolah", progress: 0 }, { id: "e-32", type: "PROGRESS_UPDATED", date: "15 Jan 2026", note: "Pendaftaran resmi & penempatan di PKBM Harapan Bangsa", progress: 70 }, { id: "e-33", type: "COMPLETED", date: "22 Jan 2026", note: "Penyerahan seragam, modul Paket C, & biaya operasional", progress: 100 }] },
];

function mapStatus(status: string): DisdikReferralStatus { if (status === "SELESAI") return "SELESAI"; if (status === "DITERIMA" || status === "DIPROSES") return "DALAM_PROSES"; return "PERLU_DIPROSES"; }
export async function getDisdikSchools(): Promise<DisdikSchool[]> { if (previewEnabled) return previewSchools; const admin = createAdminClient(); const result = await admin.from("disdik_sekolah").select("id,kode,nama,jenjang,kelurahan,alamat").eq("is_active", true).order("nama"); fail(result.error, "Master sekolah Disdik tidak tersedia"); return (result.data ?? []).map((row) => ({ id: row.id, code: row.kode, name: row.nama, level: row.jenjang, kelurahan: row.kelurahan ?? "—", address: row.alamat ?? "Kota Bandung" })); }

export async function getDisdikPrograms(): Promise<DisdikProgram[]> {
  if (previewEnabled) return previewPrograms; const admin = createAdminClient(); const opd = await admin.from("master_opd").select("id").eq("kode_opd", "DISDIK").single(); fail(opd.error, "Master OPD DISDIK tidak tersedia"); if (!opd.data) throw new Error("Master OPD DISDIK tidak tersedia.");
  const programs = await admin.from("master_program_layanan").select("id,kode_program,nama_program,is_active").eq("opd_id", opd.data.id).eq("jalur", "PENGUATAN_DASAR").order("nama_program"); fail(programs.error, "Program Disdik tidak dapat dibaca"); if (!programs.data?.length) return [];
  const ids = programs.data.map((row) => row.id); const [details, interventions] = await Promise.all([admin.from("disdik_program_details").select("program_id,jenjang_target,jenis_bantuan,sekolah_id,duration_value,duration_unit,execution_date,budget_per_student,capacity,description").in("program_id", ids), admin.from("disdik_interventions").select("program_id,aid_status").in("program_id", ids).neq("aid_status", "TIDAK_AKTIF")]); fail(details.error, "Detail program Disdik tidak dapat dibaca"); fail(interventions.error, "Kuota program Disdik tidak dapat dihitung");
  const detailMap = new Map((details.data ?? []).map((row) => [row.program_id, row])); const schoolIds = [...new Set((details.data ?? []).map((row) => row.sekolah_id))]; const schools = schoolIds.length ? await admin.from("disdik_sekolah").select("id,nama,kelurahan,alamat").in("id", schoolIds) : { data: [], error: null }; fail(schools.error, "Sekolah program Disdik tidak dapat dibaca"); const schoolMap = new Map((schools.data ?? []).map((row) => [row.id, row])); const filled = new Map<string, number>(); for (const row of interventions.data ?? []) filled.set(row.program_id, (filled.get(row.program_id) ?? 0) + 1);
  return programs.data.map((program) => { const detail = detailMap.get(program.id); if (!detail) throw new Error(`Program ${program.kode_program} belum memiliki detail canonical.`); const school = schoolMap.get(detail.sekolah_id); if (!school) throw new Error(`Sekolah program ${program.kode_program} tidak ditemukan.`); const occupied = filled.get(program.id) ?? 0; return { id: program.id, code: program.kode_program, name: program.nama_program, level: detail.jenjang_target, aidType: detail.jenis_bantuan, schoolId: detail.sekolah_id, school: school.nama, duration: `${detail.duration_value} ${detail.duration_unit.charAt(0)}${detail.duration_unit.slice(1).toLowerCase()}`, executionDate: formatDate(detail.execution_date), budgetPerStudent: Number(detail.budget_per_student), filled: occupied, capacity: detail.capacity, status: !program.is_active ? "NONAKTIF" : occupied >= detail.capacity ? "PENUH" : "AKTIF", location: school.kelurahan ?? school.alamat ?? "Kota Bandung", description: detail.description }; });
}

export async function getDisdikReferrals(): Promise<DisdikReferral[]> {
  if (previewEnabled) return previewReferrals; const admin = createAdminClient(); const opd = await admin.from("master_opd").select("id").eq("kode_opd", "DISDIK").single(); fail(opd.error, "Master OPD DISDIK tidak tersedia"); if (!opd.data) throw new Error("Master OPD DISDIK tidak tersedia.");
  const referralResult = await admin.from("referral_mbi").select("id,referral_code,warga_id,program_id,status,referral_date,sent_at,target_program,instruction").eq("target_opd_id", opd.data.id).eq("referral_type", "JALUR_MBI").eq("jalur", "PENGUATAN_DASAR").neq("status", "DIBATALKAN").order("created_at", { ascending: false }).limit(100); fail(referralResult.error, "Referral Disdik tidak dapat dibaca"); const referrals = referralResult.data ?? []; if (!referrals.length) return [];
  const referralIds = referrals.map((row) => row.id); const wargaIds = [...new Set(referrals.map((row) => row.warga_id))]; const interventions = await admin.from("disdik_interventions").select("id,referral_id,program_id,sekolah_id,start_date,jenjang_siswa,aid_status,document_status,progress_percent,planned_budget,aid_item,evaluation_note").in("referral_id", referralIds); fail(interventions.error, "Intervensi Disdik tidak dapat dibaca"); const interventionRows = interventions.data ?? []; const interventionIds = interventionRows.map((row) => row.id); const programIds = [...new Set([...referrals.map((row) => row.program_id), ...interventionRows.map((row) => row.program_id)].filter(Boolean))]; const schoolIds = [...new Set(interventionRows.map((row) => row.sekolah_id).filter(Boolean))];
  const [warga, desil, programs, schools, events, realizations] = await Promise.all([admin.from("warga").select("id,nik,nama_lengkap,kelurahan,pendidikan_terakhir").in("id", wargaIds), admin.from("penetapan_desil").select("warga_id,desil_dtsen,created_at").in("warga_id", wargaIds).order("created_at", { ascending: false }), programIds.length ? admin.from("master_program_layanan").select("id,nama_program").in("id", programIds) : Promise.resolve({ data: [], error: null }), schoolIds.length ? admin.from("disdik_sekolah").select("id,nama").in("id", schoolIds) : Promise.resolve({ data: [], error: null }), interventionIds.length ? admin.from("disdik_intervention_events").select("id,intervention_id,event_type,event_at,note,progress_percent").in("intervention_id", interventionIds).order("event_at", { ascending: true }) : Promise.resolve({ data: [], error: null }), interventionIds.length ? admin.from("disdik_realisasi_bantuan").select("intervention_id,realized_amount,aid_item,notes").in("intervention_id", interventionIds) : Promise.resolve({ data: [], error: null })]); for (const [result, context] of [[warga,"Warga referral Disdik"],[desil,"Desil referral Disdik"],[programs,"Program referral Disdik"],[schools,"Sekolah referral Disdik"],[events,"Timeline Disdik"],[realizations,"Realisasi Disdik"]] as const) fail(result.error, `${context} tidak dapat dibaca`);
  const wargaMap = new Map((warga.data ?? []).map((row) => [row.id, row])); const programMap = new Map((programs.data ?? []).map((row) => [row.id, row.nama_program])); const schoolMap = new Map((schools.data ?? []).map((row) => [row.id, row.nama])); const interventionMap = new Map(interventionRows.map((row) => [row.referral_id, row])); const realizationMap = new Map((realizations.data ?? []).map((row) => [row.intervention_id, row])); const desilMap = new Map<string, number>(); for (const row of desil.data ?? []) if (!desilMap.has(row.warga_id)) desilMap.set(row.warga_id, row.desil_dtsen ?? 0); const eventMap = new Map<string, DisdikTimelineEvent[]>(); for (const row of events.data ?? []) { const list = eventMap.get(row.intervention_id) ?? []; list.push({ id: row.id, type: row.event_type, date: formatDate(row.event_at), note: row.note ?? "—", progress: row.progress_percent }); eventMap.set(row.intervention_id, list); }
  return referrals.flatMap((referral): DisdikReferral[] => { const citizen = wargaMap.get(referral.warga_id); if (!citizen) return []; const intervention = interventionMap.get(referral.id) ?? null; const realization = intervention ? realizationMap.get(intervention.id) : null; const programId = intervention?.program_id ?? referral.program_id; return [{ id: referral.id, interventionId: intervention?.id ?? null, code: referral.referral_code, name: citizen.nama_lengkap, maskedNik: maskNik(citizen.nik), date: formatDate(referral.referral_date ?? referral.sent_at), programId: programId ?? null, program: (programId ? programMap.get(programId) : null) ?? referral.target_program ?? "Belum dipilih", schoolId: intervention?.sekolah_id ?? null, school: intervention?.sekolah_id ? schoolMap.get(intervention.sekolah_id) ?? "—" : "Belum dipilih", level: intervention?.jenjang_siswa ?? citizen.pendidikan_terakhir ?? "Belum diketahui", desil: desilMap.get(referral.warga_id) ?? 0, kelurahan: citizen.kelurahan ?? "—", status: mapStatus(referral.status), aidStatus: intervention?.aid_status ?? null, documentStatus: intervention?.document_status ?? null, plannedBudget: Number(intervention?.planned_budget ?? 0), realizedAmount: realization ? Number(realization.realized_amount) : null, aidItem: realization?.aid_item ?? intervention?.aid_item ?? "Belum ditentukan", notes: realization?.notes ?? intervention?.evaluation_note ?? referral.instruction ?? "", progress: intervention?.progress_percent ?? null, timeline: intervention ? eventMap.get(intervention.id) ?? [] : [] }]; });
}

export async function getDisdikDashboardData() { const referrals = await getDisdikReferrals(); return { referrals, summary: { newReferrals: referrals.filter((item) => item.status === "PERLU_DIPROSES").length, processing: referrals.filter((item) => item.status === "DALAM_PROSES").length, completed: referrals.filter((item) => item.status === "SELESAI").length }, preview: previewEnabled }; }
export async function getDisdikEducationReport() { const referrals = await getDisdikReferrals(); const reports: EducationReport[] = referrals.filter((item) => item.interventionId && item.realizedAmount !== null).map((item) => ({ id: item.interventionId!, referralCode: item.code, name: item.name, maskedNik: item.maskedNik, level: item.level, kelurahan: item.kelurahan, school: item.school, program: item.program, aidItem: item.aidItem, realizedAmount: item.realizedAmount ?? 0, status: item.status === "SELESAI" ? "TERINTERVENSI_SELESAI" : "DALAM_PENYALURAN", disbursementDate: item.timeline.at(-1)?.date ?? item.date, notes: item.notes, timeline: item.timeline })); const total = reports.reduce((sum, item) => sum + item.realizedAmount, 0); return { reports, summary: { completed: reports.filter((item) => item.status === "TERINTERVENSI_SELESAI").length, totalRealization: total, averageBudget: reports.length ? Math.round(total / reports.length) : 0 } }; }
