import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { CaseHero } from "@/components/dinsos/case-hero";
import { CaseTabs } from "@/components/dinsos/case-tabs";
import { ResultActions } from "@/components/dinsos/result-actions";
import resultStyles from "@/components/dinsos/result.module.css";
import styles from "@/components/dinsos/case.module.css";
import { requireDinsosActor } from "@/lib/auth/require-dinsos-actor";
import { getDinsosCaseById } from "@/lib/dinsos/cases";

export default async function ResultPage({params}:{params:Promise<{caseId:string}>}){const {caseId}=await params;const actor=await requireDinsosActor();const item=await getDinsosCaseById(caseId,actor.profileId);if(!item)notFound();if(item.assessment?.status!=="COMPLETED")redirect(`/dinsos/kasus/${caseId}/asesmen`);const operational=Number(item.result?.operational_desil??item.officialDesil?.desil??0)||null;const confirmed=item.result?.status==="CONFIRMED";const disposition=operational===null?"Hasil Desil Belum Tersedia":operational<=2?"STABILISASI SOSIAL":"SPLIT JALUR";const scores=[['Kemiskinan','score_kemiskinan'],['Pekerjaan','score_pekerjaan'],['Pendidikan','score_pendidikan'],['Kesehatan','score_kesehatan'],['Kondisi Keluarga','score_kondisi_keluarga'],['Tempat Tinggal','score_tempat_tinggal'],['Administrasi','score_administrasi'],['Kapasitas Individu','score_kapasitas_individu']] as const;return <section><div className={styles.breadcrumb}><span>Asesmen Sosial &nbsp;/&nbsp; <strong>Hasil Desil</strong></span><Link className={styles.back} href="/dinsos">← Kembali ke Antrian</Link></div><CaseHero item={item} compact/><CaseTabs caseId={caseId} active="result" assessmentReady resultReady={confirmed}/>{item.verification?.status==="VERIFIED"&&<p className={styles.warning}>✓ Terverifikasi</p>}<div className={resultStyles.layout}><article className={resultStyles.resultCard}><div><p>Hasil {item.result?.result_source==="OVERRIDE"?"Operasional":"DTSEN Resmi"}</p>{operational?<strong>Desil {operational}</strong>:<strong>—</strong>}<span className={resultStyles.disposition}>{disposition}</span><p>{operational?operational<=2?"Warga memerlukan Proteksi dan Stabilisasi Sosial.":"Warga dapat melanjutkan ke penentuan jalur intervensi.":"Konfirmasi dinonaktifkan sampai hasil resmi tersedia."}</p></div></article><aside className={resultStyles.dimensions}><h2>Rincian 8 Dimensi</h2><p>Skor kerentanan per dimensi</p>{scores.map(([label,key])=>{const score=typeof item.assessment?.[key]==="number"?Number(item.assessment[key]):null;return <div className={resultStyles.dimension} key={key}><div><span>{label}</span><strong>{score===null?"Belum dihitung":`${score}/100`}</strong></div><div className={resultStyles.track}><span style={{width:`${score??0}%`}}/></div></div>})}</aside></div><ResultActions caseId={caseId} canOverride={item.canOverride} confirmed={confirmed} currentDesil={operational}/></section>}
