"use client";

import { ChevronLeft, ChevronRight, ClipboardList, Eye, Send, ShieldCheck, Split, Users } from "lucide-react";
import type { ReactNode } from "react";
import { useMemo, useState } from "react";

import type { KecamatanData, KecamatanCitizen } from "@/lib/kecamatan/data";
import { CitizenDrawer, ReferralDialog, ReferralDrawer, StatusBadge, SurveyAssignmentDialog, SurveyResultDialog, SurveyReviewDialog } from "@/components/kecamatan/shared/workflow-panels";
import styles from "@/components/kecamatan/shared/kecamatan-ui.module.css";

type Mode = "assign" | "result" | "review" | "referral" | "detail" | null;
function action(status: string): { label: string; mode: Exclude<Mode, null> } { if (status === "MENUNGGU_SURVEI") return { label: "Tugaskan Survei", mode: "assign" }; if (status === "SURVEI_DITUGASKAN") return { label: "Isi Hasil Survei", mode: "result" }; if (status === "MENUNGGU_PERSETUJUAN") return { label: "Review & Approve", mode: "review" }; if (status === "DISETUJUI") return { label: "Kirim ke OPD", mode: "referral" }; return { label: "Detail", mode: "detail" }; }

export function KecamatanDashboard({ data }: { data: KecamatanData }) {
  const [selected, setSelected] = useState<KecamatanCitizen | null>(null); const [mode, setMode] = useState<Mode>(null); const [search, setSearch] = useState(""); const [stage, setStage] = useState(""); const [village, setVillage] = useState("");
  const queue = useMemo(() => data.citizens.filter((item) => item.proposalId && item.proposalStatus !== "DITOLAK").filter((item) => !search || `${item.name} ${item.maskedNik}`.toLowerCase().includes(search.toLowerCase())).filter((item) => !stage || item.proposalStatus === stage).filter((item) => !village || item.kelurahanId === village), [data.citizens, search, stage, village]);
  function open(item: KecamatanCitizen, next: Exclude<Mode, null>) { setSelected(item); setMode(next); }
  function close() { setSelected(null); setMode(null); }
  return <section aria-labelledby="kc-dashboard-title"><div className={styles.pageHeading}><div><h1 id="kc-dashboard-title">Antrian Kerja Kewilayahan</h1><p>Selamat datang, Tim Kecamatan {data.actor.district}. Berikut daftar tugas verifikasi dan rujukan warga MBI.</p></div></div>
    <div className={styles.metricsGrid}><Metric label="Menunggu Verifikasi RT/RW" value={data.queueSummary.waitingSurvey} icon={<ClipboardList />} /><Metric label="Verifikasi Kelurahan" value={data.queueSummary.assignedSurvey} icon={<Users />} /><Metric label="Validasi Kecamatan" value={data.queueSummary.waitingApproval} icon={<ShieldCheck />} /><Metric label="Siap Split Jalur OPD" value={data.queueSummary.readyReferral} icon={<Split />} /><Metric label="Rujukan Terkirim Bulan Ini" value={data.queueSummary.sentThisMonth} icon={<Send />} /></div>
    <section className={styles.card}><div className={styles.filters}><h2>Antrian Kerja Hari Ini</h2><div className={styles.filterControls}><input className={styles.searchBox} aria-label="Cari antrean" placeholder="NIK atau Nama..." value={search} onChange={(event) => setSearch(event.target.value)} /><select aria-label="Filter kelurahan" value={village} onChange={(event) => setVillage(event.target.value)}><option value="">Semua Kelurahan</option>{data.kelurahan.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select aria-label="Filter tahap" value={stage} onChange={(event) => setStage(event.target.value)}><option value="">Semua Tahap</option><option value="MENUNGGU_SURVEI">Menunggu Survei</option><option value="SURVEI_DITUGASKAN">Survei Ditugaskan</option><option value="MENUNGGU_PERSETUJUAN">Validasi Kecamatan</option><option value="DISETUJUI">Siap Rujuk</option><option value="DIRUJUK">Sudah Dirujuk</option></select></div></div>
      <div className={styles.desktopTable}><table><thead><tr><th>NIK</th><th>Nama</th><th>Kelurahan</th><th>Tahap Saat Ini</th><th>Prioritas</th><th>Tanggal Masuk</th><th>Aksi</th></tr></thead><tbody>{queue.map((item) => { const next = action(item.proposalStatus); return <tr key={item.id}><td>{item.maskedNik}</td><td><strong>{item.name}</strong></td><td>{item.kelurahan}</td><td><StatusBadge status={item.proposalStatus} /></td><td><span className={`${styles.badge} ${item.desil && item.desil <= 2 ? styles.statusRed : item.desil === 3 ? styles.badgeAmber : styles.badgeGreen}`}>{item.desil && item.desil <= 2 ? "Tinggi" : item.desil === 3 ? "Sedang" : "Rendah"}</span></td><td>{item.registeredAt}</td><td><button className={`${styles.action} ${next.mode !== "detail" ? styles.actionPrimary : ""}`} onClick={() => open(item, next.mode)}>{next.mode === "detail" && <Eye size={16} />}{next.label}</button></td></tr>; })}</tbody></table></div>
      <div className={styles.mobileCards}>{queue.map((item) => { const next = action(item.proposalStatus); return <article key={item.id}><header><div><h3>{item.name}</h3><span className={styles.muted}>{item.maskedNik} · {item.kelurahan}</span></div><StatusBadge status={item.proposalStatus} /></header><dl><div><dt>Desil</dt><dd>{item.desil ?? "—"}</dd></div><div><dt>Masuk</dt><dd>{item.registeredAt}</dd></div></dl><button className={`${styles.action} ${styles.actionPrimary}`} onClick={() => open(item, next.mode)}>{next.label}</button></article>; })}</div>
      {!queue.length && <p className={styles.emptyState}>Belum ada antrean kewilayahan yang sesuai filter.</p>}<nav className={styles.pagination}><p>Menampilkan 1–{queue.length} dari {queue.length} antrean</p><div className={styles.pages}><span><ChevronLeft size={15} /></span><strong>1</strong><span><ChevronRight size={15} /></span></div></nav>
    </section>
    {selected && mode === "assign" && <SurveyAssignmentDialog citizen={selected} close={close} />}{selected && mode === "result" && <SurveyResultDialog citizen={selected} close={close} />}{selected && mode === "review" && <SurveyReviewDialog citizen={selected} programs={data.programs} close={close} />}{selected && mode === "referral" && <ReferralDialog citizen={selected} programs={data.programs} close={close} />}{selected && mode === "detail" && (selected.referral ? <ReferralDrawer citizen={selected} close={close} /> : <CitizenDrawer citizen={selected} close={close} />)}
  </section>;
}

function Metric({ label, value, icon }: { label: string; value: number; icon: ReactNode }) { return <article className={styles.metric}><span>{label}</span><strong>{value}</strong><small aria-hidden="true">{icon}</small></article>; }
