import "server-only";

import { maskNik } from "@/lib/privacy/mask-nik";
import { createAdminClient } from "@/lib/supabase/admin";

export type Dp3aReferralStatus = "PERLU_DIPROSES" | "DALAM_PROSES" | "SELESAI";
export type Dp3aCaseStatus = "VERIFIKASI" | "PENDAMPINGAN" | "SELESAI" | "TIDAK_AKTIF";
export type Dp3aVerificationStatus = "MENUNGGU" | "LULUS" | "DITOLAK";
export type Dp3aTimelineEvent = { id: string; type: "STARTED" | "PROGRESS_UPDATED" | "COMPLETED" | "CANCELLED"; date: string; note: string; progress: number | null };
export type Dp3aReferral = { id: string; caseId: string | null; code: string; name: string; maskedNik: string; date: string; programId: string | null; program: string; unitId: string | null; unit: string; serviceType: string; desil: number; kelurahan: string; kecamatan: string; status: Dp3aReferralStatus; caseStatus: Dp3aCaseStatus | null; verificationStatus: Dp3aVerificationStatus | null; plannedBudget: number; realizedAmount: number | null; supportItem: string; notes: string; progress: number | null; timeline: Dp3aTimelineEvent[] };
export type Dp3aProgram = { id: string; code: string; name: string; category: string; serviceType: string; unitId: string; unit: string; duration: string; executionDate: string; budgetPerBeneficiary: number; filled: number; capacity: number; status: "AKTIF" | "PENUH" | "NONAKTIF"; location: string; description: string };
export type Dp3aServiceUnit = { id: string; code: string; name: string; category: string; kelurahan: string; address: string };
export type Dp3aReport = { id: string; referralCode: string; name: string; maskedNik: string; serviceType: string; kelurahan: string; kecamatan: string; unit: string; program: string; supportItem: string; realizedAmount: number; status: "DALAM_PENANGANAN" | "TERINTERVENSI_SELESAI"; realizationDate: string; notes: string; timeline: Dp3aTimelineEvent[] };

export const previewEnabled = process.env.NODE_ENV !== "production" && process.env.DP3A_PREVIEW_MODE === "true";
function fail(error: { message?: string } | null, context: string) { if (error) throw new Error(`${context}: ${error.message ?? "database error"}`); }
function formatDate(value: string | null) { if (!value) return "—"; return new Intl.DateTimeFormat("id-ID", { day: "2-digit", month: "short", year: "numeric", timeZone: "Asia/Jakarta" }).format(new Date(value)); }

const previewUnits: Dp3aServiceUnit[] = [
  { id: "00000000-0000-4000-8000-000000000601", code: "UPTD-PPA-HUKUM", name: "UPTD PPA Kota Bandung — Tim Advokasi Hukum", category: "HUKUM", kelurahan: "Sukajadi", address: "Kota Bandung" },
  { id: "00000000-0000-4000-8000-000000000602", code: "UPTD-PPA-ANAK", name: "UPTD PPA — Tim Perlindungan Anak", category: "PERLINDUNGAN_ANAK", kelurahan: "Pasteur", address: "Kota Bandung" },
  { id: "00000000-0000-4000-8000-000000000603", code: "UPTD-PPA-PSI", name: "UPTD PPA & Psikolog Klinis DP3A", category: "PSIKOSOSIAL", kelurahan: "Sekeloa", address: "Kota Bandung" },
];
const previewPrograms: Dp3aProgram[] = [
  { id: "00000000-0000-4000-8000-000000000611", code: "PRG-PPA-01", name: "Fasilitasi Pendampingan Hukum & Advokasi", category: "Perlindungan Hukum", serviceType: "Pendampingan Hukum & Konseling Psikologis", unitId: previewUnits[0].id, unit: previewUnits[0].name, duration: "3 Bulan", executionDate: "15 Sep 2026", budgetPerBeneficiary: 3500000, filled: 32, capacity: 40, status: "AKTIF", location: "Kota Bandung", description: "Pendampingan hukum, advokasi, dan pemulihan psikososial bagi perempuan dan anak rentan." },
  { id: "00000000-0000-4000-8000-000000000612", code: "PRG-PPA-02", name: "Konseling Psikologis & Pemulihan Trauma", category: "Kesehatan Mental", serviceType: "Konseling Psikologis & Pemulihan Trauma", unitId: previewUnits[2].id, unit: previewUnits[2].name, duration: "2 Bulan", executionDate: "01 Okt 2026", budgetPerBeneficiary: 3500000, filled: 50, capacity: 50, status: "PENUH", location: "Kota Bandung", description: "Sesi konseling intensif, pendampingan trauma, dan layanan klinis." },
  { id: "00000000-0000-4000-8000-000000000613", code: "PRG-PPA-03", name: "Pemberdayaan Ekonomi Perempuan Rentan (PEKKA)", category: "Pemberdayaan Ekonomi", serviceType: "Konseling & Ekonomi", unitId: previewUnits[2].id, unit: previewUnits[2].name, duration: "3 Bulan", executionDate: "10 Nov 2026", budgetPerBeneficiary: 3500000, filled: 38, capacity: 60, status: "AKTIF", location: "Kota Bandung", description: "Pemulihan serta dukungan usaha untuk perempuan kepala keluarga dan penyintas kekerasan." },
];
const previewReferrals: Dp3aReferral[] = [
  { id: "00000000-0000-4000-8000-000000000621", caseId: null, code: "KSS-PPA-2026-101", name: "Dewi Sartika", maskedNik: "32731255xxxx8899", date: "14 Feb 2026", programId: previewPrograms[0].id, program: previewPrograms[0].name, unitId: previewUnits[0].id, unit: previewUnits[0].name, serviceType: "Pendampingan Hukum", desil: 1, kelurahan: "Sukajadi", kecamatan: "Sukajadi", status: "PERLU_DIPROSES", caseStatus: null, verificationStatus: null, plannedBudget: 3500000, realizedAmount: null, supportItem: "Pendampingan hukum & konseling psikologis", notes: "Berkas rujukan awal telah diverifikasi untuk pendampingan hukum dan pemulihan trauma.", progress: null, timeline: [] },
  { id: "00000000-0000-4000-8000-000000000622", caseId: "00000000-0000-4000-8000-000000000632", code: "KSS-PPA-2026-115", name: "Ananda Rizky", maskedNik: "32730455xxxx1122", date: "08 Feb 2026", programId: previewPrograms[1].id, program: previewPrograms[1].name, unitId: previewUnits[1].id, unit: previewUnits[1].name, serviceType: "Perlindungan Anak & Rumah Aman", desil: 1, kelurahan: "Pasteur", kecamatan: "Sukajadi", status: "DALAM_PROSES", caseStatus: "PENDAMPINGAN", verificationStatus: "LULUS", plannedBudget: 5000000, realizedAmount: 4200000, supportItem: "Fasilitasi safe house & pendampingan trauma healing", notes: "Penempatan rumah aman dan asesmen klinis sedang berlangsung.", progress: 75, timeline: [{ id: "ppa-21", type: "STARTED", date: "08 Feb 2026", note: "Penerimaan rujukan & evakuasi darurat anak", progress: 0 }, { id: "ppa-22", type: "PROGRESS_UPDATED", date: "01 Mar 2026", note: "Penempatan di rumah aman dan asesmen klinis", progress: 45 }, { id: "ppa-23", type: "PROGRESS_UPDATED", date: "15 Apr 2026", note: "Pendampingan psikososial & rehabilitasi khusus", progress: 75 }] },
  { id: "00000000-0000-4000-8000-000000000623", caseId: "00000000-0000-4000-8000-000000000633", code: "KSS-PPA-2026-078", name: "Siti Rahmawati", maskedNik: "32731012xxxx3344", date: "22 Jan 2026", programId: previewPrograms[2].id, program: previewPrograms[2].name, unitId: previewUnits[2].id, unit: previewUnits[2].name, serviceType: "Konseling Psikologis & Ekonomi", desil: 1, kelurahan: "Sekeloa", kecamatan: "Coblong", status: "SELESAI", caseStatus: "SELESAI", verificationStatus: "LULUS", plannedBudget: 3500000, realizedAmount: 3500000, supportItem: "Konseling psikologis & modal usaha mandiri", notes: "Pemulihan tuntas dan warga telah mandiri.", progress: 100, timeline: [{ id: "ppa-31", type: "STARTED", date: "22 Jan 2026", note: "Penerimaan rujukan & asesmen awal kebutuhan psikososial", progress: 0 }, { id: "ppa-32", type: "PROGRESS_UPDATED", date: "05 Feb 2026", note: "Sesi konseling psikologis & pendampingan pemulihan trauma", progress: 70 }, { id: "ppa-33", type: "COMPLETED", date: "22 Feb 2026", note: "Penyerahan bantuan usaha ekonomi rentan & penutupan kasus", progress: 100 }] },
];

function mapStatus(status: string): Dp3aReferralStatus { if (status === "SELESAI") return "SELESAI"; if (status === "DITERIMA" || status === "DIPROSES") return "DALAM_PROSES"; return "PERLU_DIPROSES"; }

export async function getDp3aServiceUnits(): Promise<Dp3aServiceUnit[]> {
  if (previewEnabled) return previewUnits;
  const admin = createAdminClient(); const result = await admin.from("dp3a_unit_layanan").select("id,kode,nama,kategori,kelurahan,alamat").eq("is_active", true).order("nama"); fail(result.error, "Master unit layanan DP3A tidak tersedia");
  return (result.data ?? []).map((row) => ({ id: row.id, code: row.kode, name: row.nama, category: row.kategori, kelurahan: row.kelurahan ?? "—", address: row.alamat ?? "Kota Bandung" }));
}

export async function getDp3aPrograms(): Promise<Dp3aProgram[]> {
  if (previewEnabled) return previewPrograms;
  const admin = createAdminClient(); const opd = await admin.from("master_opd").select("id").eq("kode_opd", "DP3A").single(); fail(opd.error, "Master OPD DP3A tidak tersedia"); if (!opd.data) throw new Error("Master OPD DP3A tidak tersedia.");
  const programs = await admin.from("master_program_layanan").select("id,kode_program,nama_program,is_active").eq("opd_id", opd.data.id).eq("jalur", "PENGUATAN_DASAR").order("nama_program"); fail(programs.error, "Program DP3A tidak dapat dibaca"); if (!programs.data?.length) return [];
  const ids = programs.data.map((row) => row.id); const [details, cases] = await Promise.all([admin.from("dp3a_program_details").select("program_id,kategori_target,jenis_layanan,unit_id,duration_value,duration_unit,execution_date,budget_per_beneficiary,capacity,description").in("program_id", ids), admin.from("dp3a_cases").select("program_id,case_status").in("program_id", ids).neq("case_status", "TIDAK_AKTIF")]); fail(details.error, "Detail program DP3A tidak dapat dibaca"); fail(cases.error, "Kuota program DP3A tidak dapat dihitung");
  const detailMap = new Map((details.data ?? []).map((row) => [row.program_id, row])); const unitIds = [...new Set((details.data ?? []).map((row) => row.unit_id))]; const units = unitIds.length ? await admin.from("dp3a_unit_layanan").select("id,nama,kelurahan,alamat").in("id", unitIds) : { data: [], error: null }; fail(units.error, "Unit program DP3A tidak dapat dibaca"); const unitMap = new Map((units.data ?? []).map((row) => [row.id, row])); const filled = new Map<string, number>(); for (const row of cases.data ?? []) filled.set(row.program_id, (filled.get(row.program_id) ?? 0) + 1);
  return programs.data.map((program) => { const detail = detailMap.get(program.id); if (!detail) throw new Error(`Program ${program.kode_program} belum memiliki detail canonical.`); const unit = unitMap.get(detail.unit_id); if (!unit) throw new Error(`Unit layanan program ${program.kode_program} tidak ditemukan.`); const occupied = filled.get(program.id) ?? 0; return { id: program.id, code: program.kode_program, name: program.nama_program, category: detail.kategori_target, serviceType: detail.jenis_layanan, unitId: detail.unit_id, unit: unit.nama, duration: `${detail.duration_value} ${detail.duration_unit.charAt(0)}${detail.duration_unit.slice(1).toLowerCase()}`, executionDate: formatDate(detail.execution_date), budgetPerBeneficiary: Number(detail.budget_per_beneficiary), filled: occupied, capacity: detail.capacity, status: !program.is_active ? "NONAKTIF" : occupied >= detail.capacity ? "PENUH" : "AKTIF", location: unit.kelurahan ?? unit.alamat ?? "Kota Bandung", description: detail.description }; });
}

export async function getDp3aReferrals(): Promise<Dp3aReferral[]> {
  if (previewEnabled) return previewReferrals;
  const admin = createAdminClient(); const opd = await admin.from("master_opd").select("id").eq("kode_opd", "DP3A").single(); fail(opd.error, "Master OPD DP3A tidak tersedia"); if (!opd.data) throw new Error("Master OPD DP3A tidak tersedia.");
  const referralResult = await admin.from("referral_mbi").select("id,referral_code,warga_id,program_id,status,referral_date,sent_at,target_program,instruction").eq("target_opd_id", opd.data.id).eq("referral_type", "JALUR_MBI").eq("jalur", "PENGUATAN_DASAR").neq("status", "DIBATALKAN").order("created_at", { ascending: false }).limit(100); fail(referralResult.error, "Referral DP3A tidak dapat dibaca"); const referrals = referralResult.data ?? []; if (!referrals.length) return [];
  const referralIds = referrals.map((row) => row.id); const wargaIds = [...new Set(referrals.map((row) => row.warga_id))]; const cases = await admin.from("dp3a_cases").select("id,referral_id,program_id,unit_id,start_date,jenis_kasus,case_status,verification_status,progress_percent,planned_budget,support_item,evaluation_note").in("referral_id", referralIds); fail(cases.error, "Penanganan kasus DP3A tidak dapat dibaca"); const caseRows = cases.data ?? []; const caseIds = caseRows.map((row) => row.id); const programIds = [...new Set([...referrals.map((row) => row.program_id), ...caseRows.map((row) => row.program_id)].filter(Boolean))] as string[]; const unitIds = [...new Set(caseRows.map((row) => row.unit_id).filter(Boolean))] as string[];
  const [warga, desil, programs, units, events, realizations] = await Promise.all([admin.from("warga").select("id,nik,nama_lengkap,kelurahan,kecamatan").in("id", wargaIds), admin.from("penetapan_desil").select("warga_id,desil_dtsen,created_at").in("warga_id", wargaIds).order("created_at", { ascending: false }), programIds.length ? admin.from("master_program_layanan").select("id,nama_program,jenis_intervensi").in("id", programIds) : Promise.resolve({ data: [], error: null }), unitIds.length ? admin.from("dp3a_unit_layanan").select("id,nama").in("id", unitIds) : Promise.resolve({ data: [], error: null }), caseIds.length ? admin.from("dp3a_case_events").select("id,case_id,event_type,event_at,note,progress_percent").in("case_id", caseIds).order("event_at", { ascending: true }) : Promise.resolve({ data: [], error: null }), caseIds.length ? admin.from("dp3a_realisasi_layanan").select("case_id,realized_amount,support_item,notes,realization_date").in("case_id", caseIds) : Promise.resolve({ data: [], error: null })]); for (const [result, context] of [[warga, "Warga referral DP3A"], [desil, "Desil referral DP3A"], [programs, "Program referral DP3A"], [units, "Unit referral DP3A"], [events, "Timeline DP3A"], [realizations, "Realisasi DP3A"]] as const) fail(result.error, `${context} tidak dapat dibaca`);
  const wargaMap = new Map((warga.data ?? []).map((row) => [row.id, row])); const desilMap = new Map<string, number>(); for (const row of desil.data ?? []) if (!desilMap.has(row.warga_id)) desilMap.set(row.warga_id, Number(row.desil_dtsen ?? 0)); const programMap = new Map((programs.data ?? []).map((row) => [row.id, row])); const unitMap = new Map((units.data ?? []).map((row) => [row.id, row])); const caseMap = new Map(caseRows.map((row) => [row.referral_id, row])); const realizationMap = new Map((realizations.data ?? []).map((row) => [row.case_id, row]));
  return referrals.map((referral) => { const citizen = wargaMap.get(referral.warga_id); if (!citizen) throw new Error(`Warga referral ${referral.referral_code} tidak ditemukan.`); const caseRecord = caseMap.get(referral.id); const program = programMap.get(caseRecord?.program_id ?? referral.program_id ?? ""); const unit = unitMap.get(caseRecord?.unit_id ?? ""); const realization = caseRecord ? realizationMap.get(caseRecord.id) : null; const timeline = caseRecord ? (events.data ?? []).filter((row) => row.case_id === caseRecord.id).map((row) => ({ id: row.id, type: row.event_type as Dp3aTimelineEvent["type"], date: formatDate(row.event_at), note: row.note ?? "Pembaruan penanganan DP3A.", progress: row.progress_percent })) : []; return { id: referral.id, caseId: caseRecord?.id ?? null, code: referral.referral_code, name: citizen.nama_lengkap, maskedNik: maskNik(citizen.nik), date: formatDate(referral.sent_at ?? referral.referral_date), programId: caseRecord?.program_id ?? referral.program_id, program: program?.nama_program ?? referral.target_program ?? "Layanan DP3A", unitId: caseRecord?.unit_id ?? null, unit: unit?.nama ?? "UPTD PPA Kota Bandung", serviceType: caseRecord?.jenis_kasus ?? program?.jenis_intervensi ?? referral.target_program ?? "Perlindungan & Pendampingan", desil: desilMap.get(referral.warga_id) ?? 0, kelurahan: citizen.kelurahan ?? "—", kecamatan: citizen.kecamatan ?? "—", status: mapStatus(referral.status), caseStatus: (caseRecord?.case_status as Dp3aCaseStatus | undefined) ?? null, verificationStatus: (caseRecord?.verification_status as Dp3aVerificationStatus | undefined) ?? null, plannedBudget: Number(caseRecord?.planned_budget ?? 0), realizedAmount: realization ? Number(realization.realized_amount) : null, supportItem: realization?.support_item ?? caseRecord?.support_item ?? program?.jenis_intervensi ?? "Pendampingan DP3A", notes: realization?.notes ?? caseRecord?.evaluation_note ?? referral.instruction ?? "Rujukan menunggu verifikasi DP3A.", progress: caseRecord?.progress_percent ?? null, timeline }; });
}

export async function getDp3aDashboardData() { const referrals = await getDp3aReferrals(); return { referrals, summary: { newReferrals: referrals.filter((item) => item.status === "PERLU_DIPROSES").length, processing: referrals.filter((item) => item.status === "DALAM_PROSES").length, completed: referrals.filter((item) => item.status === "SELESAI").length }, preview: previewEnabled }; }
export async function getDp3aReport() { const referrals = await getDp3aReferrals(); const reports: Dp3aReport[] = referrals.filter((item) => item.caseId && item.realizedAmount !== null).map((item) => ({ id: item.caseId!, referralCode: item.code, name: item.name, maskedNik: item.maskedNik, serviceType: item.serviceType, kelurahan: item.kelurahan, kecamatan: item.kecamatan, unit: item.unit, program: item.program, supportItem: item.supportItem, realizedAmount: item.realizedAmount ?? 0, status: item.status === "SELESAI" ? "TERINTERVENSI_SELESAI" : "DALAM_PENANGANAN", realizationDate: item.timeline.at(-1)?.date ?? item.date, notes: item.notes, timeline: item.timeline })); const total = reports.reduce((sum, item) => sum + item.realizedAmount, 0); return { reports, summary: { completed: reports.filter((item) => item.status === "TERINTERVENSI_SELESAI").length, totalRealization: total, averageBudget: reports.length ? Math.round(total / reports.length) : 0 } }; }
