"use client";

import { BookOpenCheck, ChevronLeft, ChevronRight, Eye, GraduationCap, Plus, Search, UsersRound } from "lucide-react";
import { useMemo, useState } from "react";
import { Dialog, Drawer } from "@/components/disdik/shared/dialog";
import styles from "@/components/disdik/shared/disdik-ui.module.css";
import type { DisdikProgram, DisdikReferral, DisdikSchool } from "@/lib/disdik/data";

type Modal = "add" | "manage" | "detail" | null;
function rupiah(value: number) { return new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 }).format(value); }
export function ProgramCatalog({ initialPrograms, referrals, schools, preview }: { initialPrograms: DisdikProgram[]; referrals: DisdikReferral[]; schools: DisdikSchool[]; preview: boolean }) {
  const [programs, setPrograms] = useState(initialPrograms); const [selected, setSelected] = useState<DisdikProgram | null>(null); const [modal, setModal] = useState<Modal>(null); const [query, setQuery] = useState(""); const [status, setStatus] = useState(""); const [level, setLevel] = useState(""); const [notice, setNotice] = useState("");
  const filtered = useMemo(() => programs.filter((item) => { const haystack = `${item.code} ${item.name} ${item.school}`.toLowerCase(); return (!query || haystack.includes(query.toLowerCase())) && (!status || item.status === status) && (!level || item.level.includes(level)); }), [programs, query, status, level]);
  const participants = selected ? referrals.filter((item) => item.programId === selected.id && item.interventionId) : [];
  function close() { setModal(null); setSelected(null); setNotice(""); }
  async function addProgram(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); let body: { programId?: string; error?: string } = {}; if (!preview) { const response = await fetch("/api/disdik/programs", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(Object.fromEntries(form)) }); body = await response.json().catch(() => ({})); if (!response.ok) return setNotice(body.error ?? "Program tidak dapat disimpan."); } const school = schools.find((x) => x.id === form.get("schoolId")); setPrograms((items) => [...items, { id: body.programId ?? crypto.randomUUID(), code: String(form.get("code")), name: String(form.get("name")), level: String(form.get("level")), aidType: String(form.get("aidType")), schoolId: school?.id ?? "", school: school?.name ?? "—", duration: `${form.get("duration")} ${form.get("durationUnit")}`, executionDate: String(form.get("executionDate")), budgetPerStudent: Number(form.get("budgetPerStudent")), filled: 0, capacity: Number(form.get("capacity")), status: "AKTIF", location: school?.kelurahan ?? "Kota Bandung", description: String(form.get("description")) }]); setNotice(preview ? "Program demo ditambahkan untuk sesi ini." : "Program pendidikan diterbitkan."); window.setTimeout(close, 500); }
  return <section aria-labelledby="program-title"><div className={styles.pageHeading}><div><h1 id="program-title">Katalog Program / Bantuan Pendidikan</h1><p>Pengelolaan program beasiswa, bantuan perlengkapan sekolah, pendidikan kesetaraan, dan kuota penerima MBI.</p></div><button className={styles.primary} onClick={() => setModal("add")}><Plus size={17} /> Tambah Program</button></div>
    <div className={styles.summaryGrid}><article className={styles.summaryCard}><span className={styles.summaryIcon}><BookOpenCheck size={27} /></span><div><p>Program Aktif</p><strong>{programs.filter((x) => x.status === "AKTIF").length}</strong></div></article><article className={styles.summaryCard}><span className={styles.summaryIcon}><UsersRound size={27} /></span><div><p>Total Kuota Siswa</p><strong>{programs.reduce((sum, x) => sum + x.capacity, 0)}</strong></div></article><article className={styles.summaryCard}><span className={styles.summaryIcon}><GraduationCap size={27} /></span><div><p>Penerima MBI Terdaftar</p><strong>{programs.reduce((sum, x) => sum + x.filled, 0)}</strong></div></article></div>
    <section className={styles.card}><div className={styles.filters}><label style={{ position: "relative" }}><Search size={17} style={{ position: "absolute", left: 12, top: 12 }} /><input style={{ paddingLeft: 40, minWidth: 430 }} aria-label="Cari program" placeholder="Cari nama program, kode, atau sekolah..." value={query} onChange={(e) => setQuery(e.target.value)} /></label><div className={styles.filterControls}><select aria-label="Filter jenjang program" value={level} onChange={(e) => setLevel(e.target.value)}><option value="">Semua Jenjang</option><option>SD</option><option>SMP</option><option>Kesetaraan</option></select><select aria-label="Filter status program" value={status} onChange={(e) => setStatus(e.target.value)}><option value="">Semua Status</option><option>AKTIF</option><option>PENUH</option><option>NONAKTIF</option></select></div></div>
      <div className={styles.desktopTable}><table><thead><tr><th>Kode &amp; Nama Program</th><th>Sekolah / Penyelenggara</th><th>Durasi</th><th>Kuota Terisi</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{filtered.map((item) => <tr key={item.id}><td><strong>{item.name}</strong><span className={styles.muted}>{item.code}</span></td><td>{item.school}<br /><span className={styles.muted}>{item.location}</span></td><td>{item.duration}</td><td><span className={styles.progressTrack}><span style={{ width: `${Math.min(100, item.filled / item.capacity * 100)}%`, background: item.status === "PENUH" ? "#947000" : "#0d4fa3" }} /></span>{item.filled} / {item.capacity}</td><td><span className={`${styles.badge} ${item.status === "PENUH" ? styles.badgeAmber : styles.badgeGreen}`}>{item.status}</span></td><td><button className={`${styles.action} ${item.status === "AKTIF" ? styles.actionPrimary : ""}`} onClick={() => { setSelected(item); setModal(item.status === "AKTIF" ? "manage" : "detail"); }}>{item.status === "AKTIF" ? "Kelola Penerima" : <><Eye size={16} /> Detail</>}</button></td></tr>)}</tbody></table></div>
      <div className={styles.mobileCards}>{filtered.map((item) => <article key={item.id}><header><div><h3>{item.name}</h3><span className={styles.muted}>{item.code}</span></div><span className={`${styles.badge} ${item.status === "PENUH" ? styles.badgeAmber : styles.badgeGreen}`}>{item.status}</span></header><dl><div><dt>Sekolah</dt><dd>{item.school}</dd></div><div><dt>Kuota</dt><dd>{item.filled}/{item.capacity}</dd></div></dl><button className={styles.action} onClick={() => { setSelected(item); setModal(item.status === "AKTIF" ? "manage" : "detail"); }}>Lihat Program</button></article>)}</div><nav className={styles.pagination}><p>Menampilkan 1–{filtered.length} dari {programs.length} data</p><div className={styles.pages}><span><ChevronLeft size={15} /></span><strong>1</strong><span><ChevronRight size={15} /></span></div></nav></section>
    {modal === "add" && <Dialog title="Tambah Program / Bantuan Pendidikan Baru" close={close} footer={<><button className={styles.secondary} onClick={close}>Batal</button><button className={styles.primary} type="submit" form="add-program">Simpan &amp; Terbitkan Program</button></>}><form id="add-program" className={styles.form} onSubmit={addProgram}><div className={styles.twoColumns}><label>Kode Program<input name="code" placeholder="PRG-EDU-04" pattern="PRG-EDU-[0-9]{2}" required /></label><label>Nama Program / Bantuan<input name="name" minLength={5} maxLength={200} required /></label></div><div className={styles.twoColumns}><label>Jenjang Target<input name="level" placeholder="SD & SMP" required /></label><label>Jenis Bantuan<input name="aidType" placeholder="Beasiswa DSP & Operasional" required /></label></div><label>Sekolah / Penyelenggara<select name="schoolId" required>{schools.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><div className={styles.twoColumns}><label>Durasi<input name="duration" type="number" min="1" max="60" defaultValue="3" required /></label><label>Satuan<select name="durationUnit" defaultValue="BULAN"><option value="HARI">Hari</option><option value="MINGGU">Minggu</option><option value="BULAN">Bulan</option></select></label></div><label>Tanggal Pelaksanaan<input name="executionDate" type="date" required /></label><div className={styles.twoColumns}><label>Pagu Anggaran per Siswa<input name="budgetPerStudent" type="number" min="0" required /></label><label>Total Kuota<input name="capacity" type="number" min="1" max="10000" required /></label></div><label>Deskripsi &amp; Kriteria Kelayakan<textarea name="description" minLength={10} maxLength={3000} required /></label>{notice && <p role="status">{notice}</p>}</form></Dialog>}
    {selected && modal === "manage" && <Dialog wide title={`Kelola Penerima Program — ${selected.code}`} close={close} footer={<button className={styles.secondary} onClick={close}>Tutup</button>}><div className={styles.detailStack}><div className={styles.identity}><small>Nama Program</small><h3>{selected.name}</h3><p>{selected.school} · {selected.executionDate} · {rupiah(selected.budgetPerStudent)} / siswa</p><span className={`${styles.badge} ${styles.badgeGreen}`}>Aktif ({selected.filled}/{selected.capacity})</span></div><section><h2>Daftar Penerima Manfaat</h2><div className={styles.desktopTable}><table><thead><tr><th>NIK &amp; Nama Siswa</th><th>Jenjang &amp; Sekolah</th><th>Status Bantuan</th></tr></thead><tbody>{participants.map((item) => <tr key={item.id}><td><strong>{item.name}</strong><span className={styles.muted}>{item.maskedNik}</span></td><td>{item.level}<br /><span className={styles.muted}>{item.school}</span></td><td><span className={styles.badge}>{item.status === "SELESAI" ? "Selesai" : "Dalam Proses"}</span></td></tr>)}</tbody></table></div>{!participants.length && <p className={styles.emptyState}>Belum ada penerima pada program ini.</p>}</section></div></Dialog>}
    {selected && modal === "detail" && <Drawer title={`Detail Program Pendidikan — ${selected.code}`} close={close} footer={<button className={styles.secondary} onClick={close}>Tutup</button>}><div className={styles.detailStack}><div className={styles.identity}><small>Profil Program</small><h3>{selected.name}</h3><p>{selected.school}</p><span className={`${styles.badge} ${styles.badgeAmber}`}>{selected.status} ({selected.filled}/{selected.capacity})</span></div><div className={styles.detailBox}><small>Jenjang &amp; Jenis Bantuan</small><strong>{selected.level} — {selected.aidType}</strong></div><div className={styles.detailBox}><small>Durasi &amp; Pelaksanaan</small><strong>{selected.duration} · {selected.executionDate}</strong></div><div className={styles.detailBox}><small>Pagu per Siswa</small><strong>{rupiah(selected.budgetPerStudent)}</strong></div><p>{selected.description}</p></div></Drawer>}
  </section>;
}
